        MACRO-80 3.43   27-Jul-81       PAGE    1


                                ;------------------------
                                ;  C:\BIOSINT.MAC
                                ;  Winterhalter Z84C015 System
                                ;  Entwicklungssystem
                                ;------------------------
                                ; BIOS fuer HW-CPU
                                ; PROZESSOR Z84C015 von ZILOG
                                ; MIT 128K SRAM 32K EPROM, 2k I/O SRAM RTC =M48T02
                                ; FDC, IDE, ECB-BUS
                                ;
                                ; AUTOR: Hansjoerg Winterhalter
                                ; Vers. 1.0                           16.06.2003
                                ; SD-Karte 1.0                        19.11.2006
                                ; LW IDE-HD IDE CONTROLLER-KARTE      21.06.2009        
                                ; ERWEITERUNG FUER HDD LBA-MODE 16BIT 14.09.2016
                                ; NACHTRAG ERROR WRITE EXTERN         30.12.2016
                                ;
                                ; SD-KARTE ADRESSE IN BLOECKE AUFGETEILT NICHT MEHR SEQUENZIAL 30.05.2008
                                ; SEKTOR, TRACK AUS 16BIT UMSTELLEN    05.06.2016
                                ; MMC SEC/TRK BERECHNUNG LINEAR 1,2,3,4,5, AUFSTEIGEND 30.09.2017
                                ;------------------------
                                
  0000'                         ASEG
                                
                                .Z80
                                
                                ORG 0H
                                
                                ;DISPLAY EQU 1          ; 1= MIT LCD-DISPLAY
                                
  0000                          RAMSTART EQU 0000H
                                
                                ; SET CP/M LOW MEMORY DATA, VECTOR AND BUFFER ADDRESS
                                
  0003                          IOBYTE  EQU RAMSTART + 03H
  0004                          USRDRV  EQU RAMSTART + 04H
  0005                          BDOSEN  EQU RAMSTART + 05H
  005C                          TPAFCB  EQU RAMSTART + 5CH
  0080                          TPABUF  EQU RAMSTART + 80H
                                
  8000                          RAM     EQU RAMSTART + 8000H
                                
                                ;---------------------------
                                ; PERIPERIE I/O ADDRESS
                         C      INCLUDE Z84C15H.MAC
                         C      ;--------------------------
                         C      ; BIOS Hardware CS Adresse
                         C      ; Z84C15 PERIFERIE
                         C      ; 22.09.2018 Hansjoerg Winterhalter
                         C      ;
  0018                   C      SIOA    EQU 18H         ; SIOA DATA REGISTER (84C43)
                         C                              ; SIOA +1 CONTROLL REGISTER
  001A                   C      SIOB    EQU 1AH         ; SIOB DATA REGISTER (84C43)
                         C                              ; SIOB +1 CONTROLL REGISTER
  0010                   C      CTC0    EQU 10H         ; CTC    CH0 CONTROLL REGISTER (84C30)
  0011                   C      CTC1    EQU 11H         ; CTC +1 CH1 CONTROLL REGISTER (84C30)
        MACRO-80 3.43   27-Jul-81       PAGE    1-1


  0012                   C      CTC2    EQU 12H         ; CTC +2 CH2 CONTROLL REGISTER (84C30)
  0013                   C      CTC3    EQU 13H         ; CTC +3 CH3 CONTROLL REGISTER (84C30)
  001C                   C      PIOA    EQU 1CH         ; PIOA DATA REGISTER (84C20)
                         C                              ; PIOA +1 COMMAND REGISTER
  001E                   C      PIOB    EQU 1EH         ; PIOB DATA REGISTER (84C20)
                         C                              ; PIOB +1 COMMAND REGISTER
                         C      ;---------------
  00F0                   C      WDTMR   EQU 0F0H        ; MASTER REGISTER WATCH DOG TIMER
  00F1                   C      WDTCR   EQU 0F1H        ; CONTROLL REGISTER
  00F4                   C      DCI     EQU 0F4H        ; DAISY-CAINE-INTRRUPT
                         C      ;---------------
  00EE                   C      SCRP    EQU 0EEH        ; SYSTEM CONTROLL REGISTER POINTER
  00EF                   C      SCDP    EQU 0EFH        ; SYSTEM CONTROLL DATA PORT
                         C      ;---------------
                         C      ; I/O CONTROLL REGISTER ADDRESS
                         C      ; END
                         C      INCLUDE BIOSSEL.MAC
                         C      ;--------------------------
                         C      ; BIOS Hardware CS Adresse
                         C      ; IM SYSTEM HARDWARE
                         C      ;
  00F5                   C      LATCH   EQU 0F5H        ; I/O ADDRESS LATCH FOR A8-A15 EXTERN BUS
  0020                   C      SDC     EQU 20H         ; MMC KATE
  0060                   C      LCD     EQU 60H         ; LCD-DISPAY
  0080                   C      URCS    EQU 80H         ; MIT 2K SRAM A0-A4 PIOA A5-A7
                         C      
  0040                   C      EOFF    EQU 40H         ; EPROM AUS RAM <32K AKTIV
  0021                   C      RAMH    EQU 21H         ; BIT1,5 PIOA BANK1
  0000                   C      RAML    EQU 00H         ; BIT1,5 PIOA BANK0
                                ;---------------
  0020                          FDC     EQU 20H         ; SD-KARTE
  0000                          EON     EQU 0           ; BIT 6=0 PORT A EPROM EIN RAM <32K WRITE
                                ;RAMH    EQU 61H         ; BIT1,5 AN PIO A BANK 1 + EPROM AUS / INTERN
                                ;RAML    EQU 40H         ; BIT1,5 AN PIO A BANK 0 + EPROM AUS / INTERN
                                ;------------------------
  00F0                          IDE     EQU 0F0H        ; FESTPLATTE
  00F6                          IDEDOR  EQU IDE+6       ; DIGITAL OUTPUT REGISTER
  00F8                          IDEDAT  EQU IDE+8       ; DATA REGISTER
  00F9                          IDEERR  EQU IDE+9       ; ERROR REGISTER
  00FA                          IDESCNT EQU IDE+0AH     ; SEKTOR COUNT
  00FB                          IDESNUM EQU IDE+0BH     ; SEKTOR NUMBER
  00FC                          IDECLO  EQU IDE+0CH     ; CYLINDER LOW
  00FD                          IDECHI  EQU IDE+0DH     ; CYLINDER HIGH
  00FE                          IDESDH  EQU IDE+0EH     ; DRIVE AND HEAD
  00FF                          IDECMD  EQU IDE+0FH     ; COMMAND
  00FF                          IDESTAT EQU IDECMD      ; STATUS
                                
                                ;-------------------------
                                ; IDE COMMANDOS
                                
  0020                          CMD_READSEC     EQU 20H
  0030                          CMD_WRITESEC    EQU 30H
  0070                          CMD_SEEK        EQU 70H
  0090                          CMD_DIAGN       EQU 90H
  0091                          CMD_INITIA      EQU 91H
  00EC                          CMD_IDENT       EQU 0ECH
        MACRO-80 3.43   27-Jul-81       PAGE    1-2


                                ;-----------------------------
                                ; MMC INTERFACE INIT
                                
  0040                          GO_IDLE_STATE   EQU 40H
  0041                          SEND_OP_COND    EQU 41H
  0050                          SDBLOCK         EQU 50H
  0051                          READ_SINGLE_BLOCK       EQU 51H
  0058                          WRITE_BLOCK     EQU 58H
                                ;------------------------
                                ;    CTC-COMMANDOS
                                ;------------------------
                                
  0047                          BAUD1   EQU 47H         ; 9600
  0004                          TIME1   EQU 04H         ; TIME CONSTANTE
                                
  0047                          BAUD2   EQU 47H         ; TGOUT 1: 2
  0004                          TIME2   EQU 04H         ;
                                
  0047                          BAUD3   EQU 47H         ; TGOUT 1: 2
  0004                          TIME3   EQU 04H         ;
                                
  00C7                          BAUD4   EQU 0C7H        ; MIT INT /16, CLK = CLK-CPU
  000F                          TIME4   EQU 0FH         ; BAUD4 * 0FH
                                
  0015                          MSTIME  EQU 15H         ; CTC3 * MSTIME
                                
  0060                          EXOFF   EQU 60H         ; OFFSET SIO, CTC EXTEN
                                
                                ;------------------------
                                ;    SIO-COMMANDOS
                                ;------------------------
                                
  0018                          SIORES  EQU 18H         ; SIO RESET
  0004                          KANAL4  EQU 04H         ; REG 4
  0044                          REG4    EQU 44H         ; X16 CLOCK,8,SYNC
  0003                          KANAL3  EQU 03H         ; REG 3
  00C1                          REG3    EQU 0C1H        ; 8 BIT, RxENABLE
  0005                          KANAL5  EQU 05H         ; REG 5
  00EA                          REG5    EQU 0EAH        ; DTR, Tx8BIT, TxENABLE
  0001                          KANAL1  EQU 01H         ; REG 1
  0000                          REG1    EQU 00H         ; NO INT
  0000                          KANAL0  EQU 00H         ; REG 0
                                ;----------------
                                ; PORT A BIT 0 - 7 SELEKT
                                ;----------------
                                
  0007                          QA7     EQU 7H          ; IORQ =0 INT., 1= EXT.
  0006                          ELATCH  EQU 6H          ; EPROM=0, RAM=1
  0005                          TA16    EQU 5H          ; RAM 64K BANK 0=LOW, >64K 1=HIGH
  0004                          FREI    EQU 4H          ; FREI  DA KEIN -> SCSI RESRI
  0003                          RFDC    EQU 3H          ; FLOPPY RESET
  0002                          RT      EQU 2H          ; AN PAL PIN 9
  0001                          NC      EQU 1H          ; NC
  0000                          TAS     EQU 0H          ; ZU 64K BANKUNSCHALTUNG
                                
                                ;------------------------
        MACRO-80 3.43   27-Jul-81       PAGE    1-3


                                ;      START
                                ;------------------------
                                ; TESTPROGRAMM F]R 84C015 CPU
                                ;------------------------
                                
  0000    F3                            DI
  0001    C3 015C                       JP LOS
  0004    00                            NOP
                                ;---------------------------------
                                ; EIGENE BIOS SPRUNGTABELLE 0005H
                                
                                ;INCLUDE CONSOLE.MAC
                                
  0060                          SIOEX   EQU 60H         ; OFSET ZU SIO INTERN = EXTERN
                                
                                ;-----------------------------
                                ; SIOA, SIOB ADRESSE TASK HIGH
                                ; SIO A
                                
  0005    ED 73 FDA1            SIOX:   LD (STACK),SP
  0009    ED 5E                         IM 2
  000B    FB                            EI
                                        REPT 5
                                        NOP
                                        ENDM
  000C    00              +             NOP
  000D    00              +             NOP
  000E    00              +             NOP
  000F    00              +             NOP
  0010    00              +             NOP
  0011    F3                            DI
  0012    DD 2A FDA1                    LD IX,(STACK)
  0016    DD F9                         LD SP,IX
  0018    DB 1C                         IN A,(PIOA)
  001A    CB 6F                         BIT TA16,A          ; BANK0=LX, BANK1=HX
  001C    20 03                         JR NZ,SIOX1        ; EXTERN ->
  001E    0E 18                         LD C,SIOA          ; FUER INTERN
  0020    C9                            RET
                                ;------------------
                                
  0021    0E 78                 SIOX1:  LD C,SIOA+SIOEX    ; FUER EXTERN
  0023    18 1E                         JR SIOX2
                                        ;--------------
                                        ; SIO B
  0025    ED 73 FDA1            SIOY:   LD (STACK),SP
  0029    ED 5E                         IM 2
  002B    FB                            EI
                                        REPT 5
                                        NOP
                                        ENDM
  002C    00              +             NOP
  002D    00              +             NOP
  002E    00              +             NOP
  002F    00              +             NOP
  0030    00              +             NOP
  0031    F3                            DI
        MACRO-80 3.43   27-Jul-81       PAGE    1-4


  0032    DD 2A FDA1                    LD IX,(STACK)
  0036    DD F9                         LD SP,IX
  0038    DB 1C                         IN A,(PIOA)
  003A    CB 6F                         BIT TA16,A
  003C    20 03                         JR NZ,SIOY1        ; EXTERN ->
  003E    0E 1A                         LD C,SIOB          ; FUER INTERN
  0040    C9                            RET
                                        ;---------
                                        ; EXTERN UNSCHALTEN
  0041    0E 7A                 SIOY1:  LD C,SIOB+SIOEX    ; FUER EXTERN
  0043    CB FF                 SIOX2:  SET 7,A            ; SET EXTERN
  0045    D3 1C                         OUT (PIOA),A
  0047    3E 02                         LD A,02H           ; SIO KARTE 2
  0049    D3 F5                         OUT (LATCH),A
  004B    C9                            RET
                                ;-----------------------------
                                ; TX BUFFER LEER PR]FEN
                                ; ZEICHEN IN C AUSGEBEN
                                
  004C    C5                    OUT0:   PUSH BC
  004D    CD 0056                       CALL KEYRD
  0050    7B                            LD A,E
  0051    0D                            DEC C
  0052    ED 79                         OUT (C),A           ; ZEICHEN AUSGEBEN
  0054    C1                            POP BC
  0055    C9                            RET
                                ;--------------------------------
                                ; KEYREADY
                                
  0056    CD 0005               KEYRD:  CALL SIOX
  0059    0C                            INC C
  005A    3E 05                         LD A,KANAL5
  005C    ED 79                         OUT (C),A
  005E    3E EA                         LD A,REG5
  0060    CB BF                         RES 7,A             ; DTR LOW
  0062    ED 79                         OUT (C),A
                                ;----------------
                                ; PR]FE OB ZEICHEN ]BERTRAGEN UND BUFFER LEER IST
                                
  0064    ED 78                 TX2:    IN A,(C)
  0066    CB 57                         BIT 2,A             ; TRANSMISSION BUFFER EMPTY
  0068    28 FA                         JR Z,TX2
  006A    C9                            RET
                                ;--------------------------------
                                ; RX BUFFER LEER PR]FEN
                                
  006B    C5                    INP0:   PUSH BC
  006C    CD 0056               INP1:   CALL KEYRD
  006F    CB 47                         BIT 0,A         ; AUS TX2:
  0071    28 18                         JR Z,INP2       ; PRUEFE OB ZEICHEN DA ->NEIN
  0073    0D                            DEC C
  0074    ED 78                         IN A,(C)        ; SIOA ZEICHEN HOLEN
  0076    4F                            LD C,A
  0077    C5                            PUSH BC
  0078    CD 0005                       CALL SIOX
  007B    0C                            INC C
        MACRO-80 3.43   27-Jul-81       PAGE    1-5


  007C    3E 05                         LD A,KANAL5
  007E    ED 79                         OUT (C),A
  0080    3E EA                         LD A,REG5
  0082    CB BF                         RES 7,A         ; DTR HIGH
  0084    ED 79                         OUT (C),A
  0086    C1                            POP BC
  0087    79                            LD A,C
  0088    C1                            POP BC
  0089    4F                            LD C,A
  008A    C9                            RET
                                        ;----------
  008B    3E 05                 INP2:   LD A,KANAL5
  008D    ED 79                         OUT (C),A
  008F    3E EA                         LD A,REG5
  0091    CB FF                         SET 7,A             ; DTR HIGH
  0093    ED 79                         OUT (C),A
  0095    18 D5                         JR INP1
                                ;--------------------------------
                                ;  PR]FE OB TESTE GEDR]CKT
                                ;  JA: A=0FFH NEIN: A:00H
                                
  0097    C5                    PKEY:   PUSH BC
  0098    CD 0005                       CALL SIOX
  009B    0C                            INC C
  009C    06 04                         LD B,04
  009E    CD 0064               CONW:   CALL TX2
  00A1    F5                            PUSH AF
  00A2    3E 05                         LD A,KANAL5
  00A4    ED 79                         OUT (C),A
  00A6    3E EA                         LD A,REG5
  00A8    CB FF                         SET 7,A             ; DTR HIGH
  00AA    ED 79                         OUT (C),A
  00AC    F1                            POP AF
  00AD    CB 47                         BIT 0,A
  00AF    3E FF                         LD A,0FFH
  00B1    20 03                         JR NZ,CONW1             ; -> TASTE GEDRUECKT
  00B3    10 E9                         DJNZ CONW
  00B5    AF                            XOR A                   ; KEINE TASTE
  00B6    F5                    CONW1:  PUSH AF
  00B7    3E 05                         LD A,KANAL5
  00B9    ED 79                         OUT (C),A
  00BB    3E EA                         LD A,REG5
  00BD    CB BF                         RES 7,A             ; DTR HIGH
  00BF    ED 79                         OUT (C),A
  00C1    F1                            POP AF
  00C2    C1                            POP BC
  00C3    FE 00                         CP 0            ; AUS A
  00C5    4F                            LD C,A
  00C6    C9                            RET
                                
                                ;--------------------------------
                                ;  LIST DRUCKERPROGRAMM
                                ; GIBT ZEICHEN IN C AUF DRUCKER AUS
                                ; WENN NICHT BEREIT , ABBRUCH MIT TASTE
                                
  00C7    C5                    PRINT:  PUSH    BC
        MACRO-80 3.43   27-Jul-81       PAGE    1-6


  00C8    CD 00D7               LISTA:  CALL    W00
  00CB    C1                            POP BC
  00CC    41                            LD B,C                  ; C = ZEICHEN ZUM DRUCKEN
  00CD    C5                            PUSH BC
  00CE    CD 0025                       CALL    SIOY
  00D1    78                            LD      A,B
  00D2    ED 79                         OUT     (C),A           ; ZEICHEN DRUCKEN
  00D4    C1                            POP     BC
  00D5    AF                            XOR     A               ; Z=0 OK.
  00D6    C9                            RET
                                        ;-------------------
  00D7    D5                    W00:    PUSH    DE
  00D8    E5                            PUSH    HL
  00D9    CD 0025               W0:     CALL SIOY
  00DC    0C                            INC C
  00DD    11 0000                       LD      DE,0000H        ; TIMEOUT
  00E0    3E 10                 W1:     LD      A,10H           ; SET SIO REG. FUER DCD, CTS
  00E2    ED 79                         OUT     (C),A
  00E4    CD 0064                       CALL    TX2             ; READ SIO REG. 0
  00E7    CB 5F                         BIT     3,A             ; DCD
  00E9    20 28                         JR      NZ,W3           ; -> DRUCKER ONLINE
  00EB    1D                            DEC     E
  00EC    20 F2                         JR      NZ,W1
  00EE    15                            DEC     D
  00EF    20 EF                         JR      NZ,W1
  00F1    CD 0097                       CALL PKEY
  00F4    28 E3                         JR Z,W0                 ; KEINE TASTE
  00F6    CD 006B                       CALL INP0               ; ZEICHEN READ
  00F9    FE 1B                         CP 1BH                  ; ESC
  00FB    20 DC                         JR NZ,W0
  00FD    21 0116                       LD HL,ERRTEX
  0100    5E                    W4:     LD E,(HL)
  0101    7B                            LD A,E
  0102    FE FF                         CP 0FFH
  0104    28 06                         JR Z,W5
  0106    CD 004C                       CALL OUT0
  0109    23                            INC HL
  010A    18 F4                         JR W4
                                        ;------------
  010C    E1                            W5:     POP     HL
  010D    D1                            POP     DE
  010E    C1                            POP     BC
  010F    3E 01                         LD A,01
  0111    3C                            INC A           ; Z=1
  0112    C9                            RET
                                        ;-----------
  0113    E1                            W3:     POP HL
  0114    D1                            POP DE
  0115    C9                            RET             ; ZEICHEN AUSGEBEN
                                        ;------------
                                
  0116    0A 0D 07 07           ERRTEX: DEFB    0AH,0DH,7,7,7           ; CR,LF,BELL
  011A    07                    
  011B    44 72 75 63                   DEFM    'Drucker nicht bereit oder Fehler!'
  011F    6B 65 72 20           
  0123    6E 69 63 68           
        MACRO-80 3.43   27-Jul-81       PAGE    1-7


  0127    74 20 62 65           
  012B    72 65 69 74           
  012F    20 6F 64 65           
  0133    72 20 46 65           
  0137    68 6C 65 72           
  013B    21                    
  013C    0A 0D 07 07                   DEFB    0AH,0DH,7,7,7,0FFH,0FFH
  0140    07 FF FF              
                                
  0143    C5                    PLISTST: PUSH    BC
  0144    CD 0025                       CALL SIOY
  0147    0C                            INC C
  0148    3E 10                         LD A,10H        ; SIO HANDSHAKE RESET DCD, CTS
  014A    ED 79                         OUT (C),A
  014C    CD 0064                       CALL TX2
  014F    0E 00                         LD      C,0
  0151    CB 5F                         BIT     3,A
  0153    28 04                         JR      Z,NOT
  0155    3E FF                         LD      A,0FFH
  0157    C1                            POP     BC
  0158    C9                            RET
                                
  0159    AF                    NOT:    XOR     A
  015A    C1                            POP     BC
  015B    C9                            RET
                                
                                ;---------------------------------
                                ; PIO INIT PORT A
                                ; PA0,BAI1,RT,/RFDC,RSCS,TA16,LATCH,QA7
                                ; PIO INIT PORT B
                                ; PCU,U1,U2,U3,U4,U5,ND, (NC)
                                
  015C    31 B000               LOS:    LD SP,0B000H
  015F    ED 5E                         IM 2
                                        ;---------------
                                        ; PORT A
  0161    3E 0F                         LD      A,0FH           ; MODE 0 ALS AUSGANG
  0163    D3 1D                         OUT     (PIOA+1),A
  0165    3E 07                         LD      A,07H           ; KEIN INTERRUPT
  0167    D3 1D                         OUT     (PIOA+1),A
  0169    AF                            XOR     A
  016A    D3 1C                         OUT     (PIOA),A        ; PIOA = 00H, EPROM ON
                                
                                        ; PORT B
  016C    3E 0F                         LD      A,0FH           ; MODE 0 ALS AUSGANG
  016E    D3 1F                         OUT     (PIOB+1),A
  0170    3E 07                         LD      A,07H           ; KEIN INTERRUPT
  0172    D3 1F                         OUT     (PIOB+1),A
  0174    3E 3F                         LD      A,3FH           ; FUER UHR SRAM
  0176    D3 1E                         OUT     (PIOB),A        ; PIOB =00H
                                        ;---------------
                                        ; INTERRUPT COUNTER
                                        ;
  0178    3E 15                         LD      A,MSTIME        ; SET INT INTERVAL H<-> L
  017A    D3 97                         OUT     (URCS+17H),A
  017C    AF                            XOR     A
        MACRO-80 3.43   27-Jul-81       PAGE    1-8


  017D    D3 1E                         OUT     (PIOB),A        ;  PIO B =00H
                                
                                ;-------------------------------
                                ; NOCH IM EPROM
                                ;   EPROM NACH SRAM BANK0 KOPIEREN 1:1
                                
  017F    21 0000                       LD HL,0000H             ; PROG.ADR. QUELLE EPROM
  0182    11 0000                       LD DE,0000H             ; ZIEL RAM
  0185    01 8000                       LD BC,08000H            ; PROG. L[NGE 32K
  0188    ED B0                         LDIR                    ; ]BERTRGEN IN RAM BANK0
                                
                                        ;-------------------
  018A    DB 1C                         IN A,(PIOA)
  018C    CB C7                         SET TAS,A
  018E    D3 1C                         OUT (PIOA),A            ; SET SRAM WR=BANK1
                                
                                ;   EPROM NACH SRAM BANK1 KOPIEREN 1:1
  0190    21 0000                       LD HL,0000H             ; PROG.ADR. QUELLE EPROM
  0193    11 0000                       LD DE,0000H             ; ZIEL RAM
  0196    01 8000                       LD BC,08000H            ; PROG. L[NGE 32K
  0199    ED B0                         LDIR                    ; ]BERTRGEN IN RAM BANK1
                                
                                ;-------------------------------
                                ;   EPROM AUSSCHALTEN , AB HIER IM RAM
                                
  019B    3E 40                         LD A,EOFF       ; EPROM OFF
  019D    D3 1C                         OUT (PIOA),A          
                                
                                ;***************
                                ; AB HIER IM SRAM
                                ;---------------------
                                ; CTC0 INIT :16=6,51us
                                ; 1er TEILER FUER SIOA,SIOB
                                
  019F    3E 47                         LD A,BAUD1
  01A1    D3 10                         OUT (CTC0),A
  01A3    3E 04                         LD A,TIME1
  01A5    D3 10                         OUT (CTC0),A
                                
                                ;----------------------
                                ; LCD SET
                                
  01A7    3E 80                 LCDS:   LD A,80H        ; COMMAND MODE=OR-MODE & INTERNAL
  01A9    CD 02D5                       CALL LCD1       ; COMMAND MODE=OR-MODE & INTERNAL CG-ROM
                                
                                        ; GRAPHIC HOME ADRESSE
  01AC    3E 00                         LD A,00H
  01AE    CD 02D1                       CALL LCD0
  01B1    3E 00                         LD A,00H
  01B3    CD 02D1                       CALL LCD0
                                
                                        ; GRAPHIC HOME AREA
  01B6    3E 42                         LD A,42H
  01B8    CD 02D5                       CALL LCD1
  01BB    3E 1E                         LD A,1EH
  01BD    CD 02D1                       CALL LCD0
        MACRO-80 3.43   27-Jul-81       PAGE    1-9


  01C0    3E 00                         LD A,00H
  01C2    CD 02D1                       CALL LCD0
                                
                                        ; TEXT HOME ADRESSE
  01C5    3E 43                         LD A,43H
  01C7    CD 02D5                       CALL LCD1
  01CA    3E 00                         LD A,00H
  01CC    CD 02D1                       CALL LCD0
  01CF    3E 0F                         LD A,0FH
  01D1    CD 02D1                       CALL LCD0
                                
                                        ; TEXT AREA
  01D4    3E 40                         LD A,40H
  01D6    CD 02D5                       CALL LCD1
  01D9    3E 1E                         LD A,1EH
  01DB    CD 02D1                       CALL LCD0
  01DE    3E 00                         LD A,00H
  01E0    CD 02D1                       CALL LCD0
                                
  01E3    3E 41                         LD A,41H
  01E5    CD 02D5                       CALL LCD1
                                
  01E8    3E 94                         LD A,94H
  01EA    CD 02D5                       CALL LCD1
                                 
                                ;---------------------
                                ; WATCHDOG INIT
                                
  01ED    3E DB                         LD A,0DBH       ; TC=2^22
                                ;       OUT (WDTCR),A
  01EF    3E FB                         LD A,0FBH
                                ;       OUT (WDTER),A
                                ;---------------------
  01F1                          SIOS:
                                ;       KANAL 2 BAUD SIOA
  01F1    3E 47                         LD A,BAUD2
  01F3    D3 11                         OUT (CTC1),A
  01F5    3E 04                         LD A,TIME2
  01F7    D3 11                         OUT (CTC1),A
                                
                                ;       KANAL 3 BAUD SIOB
  01F9    3E 47                         LD A,BAUD3
  01FB    D3 12                         OUT (CTC2),A
  01FD    3E 04                         LD A,TIME3
  01FF    D3 12                         OUT (CTC2),A
                                ;-----------------------
                                ;   SIO 84C40 - 43  EXTERN
  0201    3E 18                         LD A,SIORES
  0203    D3 19                         OUT (SIOA+1),A          ; RESER SIO A
  0205    D3 1B                         OUT (SIOB+1),A          ; RESET SIO B
                                
  0207    3E 04                         LD A,KANAL4             ; REG 4
  0209    D3 19                         OUT (SIOA+1),A          ; REG.SELECT SIO A
  020B    D3 1B                         OUT (SIOB+1),A          ; REG.SELECT SIO B
                                
  020D    3E 44                         LD A,REG4
        MACRO-80 3.43   27-Jul-81       PAGE    1-10


  020F    D3 19                         OUT (SIOA+1),A          ; DATA SIO A
  0211    D3 1B                         OUT (SIOB+1),A          ; DATA SIO B
                                
  0213    3E 03                         LD A,KANAL3             ; REG 3
  0215    D3 19                         OUT (SIOA+1),A          ; REG.SELECT SIO A
  0217    D3 1B                         OUT (SIOB+1),A          ; REG.SELECT SIO B
                                
  0219    3E C1                         LD A,REG3
  021B    D3 19                         OUT (SIOA+1),A          ; DATA SIO A
  021D    D3 1B                         OUT (SIOB+1),A          ; DATA SIO B
                                
  021F    3E 05                         LD A,KANAL5             ; REG 5
  0221    D3 19                         OUT (SIOA+1),A          ; REG.SELECT SIO A
  0223    D3 1B                         OUT (SIOB+1),A          ; REG.SELECT SIO B
                                
  0225    3E EA                         LD A,REG5
  0227    D3 19                         OUT (SIOA+1),A          ; DATA SIO A
  0229    D3 1B                         OUT (SIOB+1),A          ; DATA SIO B
                                
  022B    3E 01                         LD A,KANAL1             ; REG 1
  022D    D3 19                         OUT (SIOA+1),A          ; REG.SELECT SIO A
  022F    D3 1B                         OUT (SIOB+1),A          ; REG.SELECT SIO B
                                
  0231    3E 00                         LD A,REG1
  0233    D3 19                         OUT (SIOA+1),A          ; DATA SIO A
  0235    D3 1B                         OUT (SIOB+1),A          ; DATA SIO B
                                
  0237    3E 00                         LD A,00H
  0239    D3 19                         OUT (SIOA+1),A
  023B    D3 1B                         OUT (SIOB+1),A
                                
                                ;---------------------
                                ; CTC 84C43 EXTERN
                                ;       KANAL 1
                                
  023D    DB 1C                         IN A,(PIOA)
  023F    CB FF                         SET QA7,A
  0241    D3 1C                         OUT (PIOA),A            ; SET EXTERN I/O
  0243    3E 02                         LD A,02H
  0245    D3 F5                         OUT (LATCH),A           ; KARTE 02 FREISCHALTEN
                                ;---------------------
                                        ; SIOA, SIOB
  0247    3E 47                         LD A,BAUD1
  0249    D3 70                         OUT (CTC0+EXOFF),A      ; REG 0
  024B    3E 04                         LD A,TIME1
  024D    D3 70                         OUT (CTC0+EXOFF),A
                                
                                ;       KANAL 2 BAUD SIOA EXT
  024F    3E 47                         LD A,BAUD2
  0251    D3 71                         OUT (CTC1+EXOFF),A
  0253    3E 04                         LD A,TIME2
  0255    D3 71                         OUT (CTC1+EXOFF),A
                                
                                ;       KANAL 3 BAUD SIOB
  0257    3E 47                         LD A,BAUD3
  0259    D3 72                         OUT (CTC2+EXOFF),A
        MACRO-80 3.43   27-Jul-81       PAGE    1-11


  025B    3E 04                         LD A,TIME3
  025D    D3 72                         OUT (CTC2+EXOFF),A
                                
                                ;   SIO 84C40 - 43  EXTERN
  025F    3E 18                         LD A,SIORES
  0261    D3 79                         OUT (SIOA+EXOFF+1),A          ; RESER SIO A
  0263    D3 7B                         OUT (SIOB+EXOFF+1),A          ; RESET SIO B
                                
  0265    3E 04                         LD A,KANAL4             ; REG 4
  0267    D3 79                         OUT (SIOA+EXOFF+1),A          ; REG.SELECT SIO A
  0269    D3 7B                         OUT (SIOB+EXOFF+1),A          ; REG.SELECT SIO B
                                
  026B    3E 44                         LD A,REG4
  026D    D3 79                         OUT (SIOA+EXOFF+1),A          ; DATA SIO A
  026F    D3 7B                         OUT (SIOB+EXOFF+1),A          ; DATA SIO B
                                
  0271    3E 03                         LD A,KANAL3             ; REG 3
  0273    D3 79                         OUT (SIOA+EXOFF+1),A          ; REG.SELECT SIO A
  0275    D3 7B                         OUT (SIOB+EXOFF+1),A          ; REG.SELECT SIO B
                                
  0277    3E C1                         LD A,REG3
  0279    D3 79                         OUT (SIOA+EXOFF+1),A          ; DATA SIO A
  027B    D3 7B                         OUT (SIOB+EXOFF+1),A          ; DATA SIO B
                                
  027D    3E 05                         LD A,KANAL5             ; REG 5
  027F    D3 79                         OUT (SIOA+EXOFF+1),A          ; REG.SELECT SIO A
  0281    D3 7B                         OUT (SIOB+EXOFF+1),A          ; REG.SELECT SIO B
                                
  0283    3E EA                         LD A,REG5
  0285    D3 79                         OUT (SIOA+EXOFF+1),A          ; DATA SIO A
  0287    D3 7B                         OUT (SIOB+EXOFF+1),A          ; DATA SIO B
                                
  0289    3E 01                         LD A,KANAL1             ; REG 1
  028B    D3 79                         OUT (SIOA+EXOFF+1),A          ; REG.SELECT SIO A
  028D    D3 7B                         OUT (SIOB+EXOFF+1),A          ; REG.SELECT SIO B
                                
  028F    3E 00                         LD A,REG1
  0291    D3 79                         OUT (SIOA+EXOFF+1),A          ; DATA SIO A
  0293    D3 7B                         OUT (SIOB+EXOFF+1),A          ; DATA SIO B
                                
  0295    3E 00                         LD A,00H
  0297    D3 79                         OUT (SIOA+EXOFF+1),A
  0299    D3 7B                         OUT (SIOB+EXOFF+1),A
                                
  029B    3E 49                         LD A,49H
  029D    D3 78                         OUT (SIOA+EXOFF),A
  029F    D3 7A                         OUT (SIOB+EXOFF),A
                                
  02A1    3E 40                         LD A,EOFF               ; EPROM OFF
  02A3    D3 1C                         OUT (PIOA),A            ; BANK0, INTERN
                                
                                ;---------------------------------
                                
  02A5    CD 02EB                       CALL LCR        ; CLEAD LCD
                                
                                        ; SETZE CURSOR HOME X, Y
        MACRO-80 3.43   27-Jul-81       PAGE    1-12


  02A8    3E 1E                         LD A,1EH
  02AA    CD 02D1                       CALL LCD0
  02AD    3E 0F                         LD A,0FH
  02AF    CD 02D1                       CALL LCD0
  02B2    3E 24                         LD A,24H
  02B4    CD 02D5                       CALL LCD1
                                
  02B7    06 14                         LD B,TXL
  02B9    21 034F                       LD HL,TEX
  02BC    CD 02C2                       CALL LCD00
                                
  02BF    C3 03C5                       JP BIOS
                                
                                ;-------------------------------
                                ; STARTTEXT AUF LCD AUSGEBEN
                                ;-------------------------------
                                
  02C2    7E                    LCD00:  LD A,(HL)
  02C3    D6 20                         SUB 20H
  02C5    CD 02D1                       CALL LCD0
  02C8    3E C0                         LD A,0C0H
  02CA    CD 02D5                       CALL LCD1
  02CD    23                            INC HL
  02CE    10 F2                         DJNZ LCD00
  02D0    C9                            RET
                                ;------------------------------
                                ; LCD READY
                                
  02D1    D3 60                 LCD0:   OUT (LCD),A
  02D3    18 02                         JR LCDRY
                                
  02D5    D3 61                 LCD1:   OUT (LCD+1),A
                                
  02D7    C5                    LCDRY:  PUSH BC
  02D8    06 10                         LD B,10H
  02DA    DB 10                 LCDRY0: IN A,(CTC0)
  02DC    B9                            CP C
  02DD    28 FB                         JR Z,LCDRY0
  02DF    4F                            LD C,A
  02E0    DB 61                 LCDRY1: IN A,(LCD+1)    ; READ COMMAND
  02E2    FE 80                         CP 80H
  02E4    28 03                         JR Z,LCDRY2
  02E6    10 F2                         DJNZ LCDRY0
  02E8    37                            SCF             ; ERROR SET CARRY
  02E9    C1                    LCDRY2: POP BC
  02EA    C9                            RET
                                ;-------------
                                
  02EB    06 03                 LCR:    LD B,03H
  02ED    0E 40                         LD C,40H
  02EF    3E 00                         LD A,00H
  02F1    CD 02D1                       CALL LCD0
  02F4    3E 0F                         LD A,0FH
  02F6    CD 02D1                       CALL LCD0
  02F9    3E 24                         LD A,24H
  02FB    CD 02D5                       CALL LCD1
        MACRO-80 3.43   27-Jul-81       PAGE    1-13


  02FE    3E 00                 CR1:    LD A,00H
  0300    CD 02D1                       CALL LCD0
  0303    3E C0                         LD A,0C0H
  0305    CD 02D5                       CALL LCD1
  0308    0D                            DEC C
  0309    20 F3                         JR NZ,CR1
  030B    10 F1                         DJNZ CR1
  030D    C9                            RET
                                
                                ;-------------------------------
                                ; TEXTAUSGABE AUF LCD
                                ; SETZE CURSOR HOME X, Y
                                
  030E                          LPOS:   ;LD A,5AH
  030E    CD 02D1                       CALL LCD0
  0311    3E 0F                         LD A,0FH
  0313    CD 02D1                       CALL LCD0
  0316    3E 24                         LD A,24H
  0318    CD 02D5                       CALL LCD1
                                
  031B    06 06                         LD B,TDRV
  031D    21 0363                       LD HL,TEXDR     ; TEST AUSGEBEN
  0320    18 A0                         JR LCD00
                                
                                ;--------------------------
                                
  0322    F5                    LHEX:   PUSH AF
  0323    C5                            PUSH BC
  0324    E5                            PUSH HL
  0325    47                            LD B,A
  0326    1F                            RRA
  0327    1F                            RRA
  0328    1F                            RRA
  0329    1F                            RRA
  032A    CD 033A                       CALL LHEX1
  032D    78                            LD A,B
  032E    CD 033A                       CALL LHEX1
  0331    3E 2E                         LD A,2EH
  0333    CD 0344                       CALL LHEX2
  0336    E1                            POP HL
  0337    C1                            POP BC
  0338    F1                            POP AF
  0339    C9                            RET
                                
                                ;-------------------------
  033A    E6 0F                 LHEX1:  AND 0FH
  033C    C6 30                         ADD A,30H
  033E    FE 3A                         CP 3AH
  0340    38 02                         JR C,LHEX2
  0342    C6 07                         ADD A,07H
  0344    D6 20                 LHEX2:  SUB 20H
  0346    CD 02D1                       CALL LCD0
  0349    3E C0                         LD A,0C0H
  034B    CD 02D5                       CALL LCD1
  034E    C9                            RET
                                
        MACRO-80 3.43   27-Jul-81       PAGE    1-14


                                ;--------------------------
                                
  034F    31 32 38 78           TEX:    DEFM '128x128 LCD-DISPLAY '
  0353    31 32 38 20           
  0357    4C 43 44 2D           
  035B    44 49 53 50           
  035F    4C 41 59 20           
  0014                          TXL     EQU $-TEX
                                
  0363    53 45 43 3D           TEXDR:  DEFM 'SEC= 0'
  0367    20 30                 
  0006                          TDRV    EQU $-TEXDR
  0369    FF                            DEFB 0FFH
                                
                                ;-------------------------------
                                ;
                                
  036A    42 69 6F 73           STEX:   DEFM 'Bios Start 16.06.07 -> 28.09.15'
  036E    20 53 74 61           
  0372    72 74 20 31           
  0376    36 2E 30 36           
  037A    2E 30 37 20           
  037E    2D 3E 20 32           
  0382    38 2E 30 39           
  0386    2E 31 35              
  001F                          LSTEX   EQU $-STEX
  0389    45 6E 64 65           ETEX:   DEFM 'Ende Uebertragung!  '
  038D    20 55 65 62           
  0391    65 72 74 72           
  0395    61 67 75 6E           
  0399    67 21 20 20           
  0014                          LETEX   EQU $-ETEX
                                
  039D    4D 4D 43 2D           SDNEU:  DEFM 'MMC-Karte Reset     '
  03A1    4B 61 72 74           
  03A5    65 20 52 65           
  03A9    73 65 74 20           
  03AD    20 20 20 20           
  03B1    4D 4D 43 20           SDOK:   DEFM 'MMC ON              '
  03B5    4F 4E 20 20           
  03B9    20 20 20 20           
  03BD    20 20 20 20           
  03C1    20 20 20 20           
  0014                          LSDOK   EQU $-SDOK
                                
                                ;--------------------------------
                                ; NOCH PR]FEN
                                
  FFA0                          TSP     EQU 0FFA0H      ; TASK STACK
  FFA2                          TASKSP  EQU TSP+2
  FFA4                          TRACKL  EQU TASKSP+2    ; 0FFA4H
  FFA5                          TRACKH  EQU TRACKL+1    ; ERWEITERUNG F]R MMC - KARTE > 33MB
  FFA6                          HSTDMA  EQU TRACKH+1    ; BUFFER PORT A (PAL)
  FFA8                          HSTSEC  EQU HSTDMA+2
  FFAA                          HSTTRK  EQU HSTSEC+2
  FFAC                          HSTDSK  EQU HSTTRK+2
        MACRO-80 3.43   27-Jul-81       PAGE    1-15


  FFAD                          DRIVE   EQU HSTDSK+1
  FFAE                          TRACKN  EQU DRIVE+1
  FFAF                          STATUS  EQU TRACKN+1
  FFB0                          NBUF    EQU STATUS+1
  FFB6                          SECBUF  EQU NBUF+6
  FFB8                          SEKTORLL        EQU SECBUF+2
  FFB9                          SEKTORLH        EQU SEKTORLL+1
  FFBA                          SEKTORHL        EQU SEKTORLH+1
  FFBB                          SEKTORHH        EQU SEKTORHL+1
                                
                                ;----------------------
                                ; BIOS EPROM SP
                                
  FFEF                          BIOSSP  EQU 0FFEFH      ; BEI SPRUNG AUS BIOS INS EPROM
                                
                                ;----------------------
                                ; BOOT PARAMETER
                                
  FFF0                          FIRST   EQU 0FFF0H      ; 0FFF0H ERSTE SPUR
  FFF1                          SA      EQU FIRST+1     ; 0FFF1H ERSTER SECTOR
  FFF2                          SM      EQU SA+1        ; 0FFF2H SEKT/TR
  FFF3                          DMA     EQU SM+1        ; 0FFF3H ANFANGSADR.
  FFF5                          ENA     EQU DMA+2       ; 0FFF5H ENDADR.
  FFF7                          STARTA  EQU ENA+2       ; 0FFF7H STARTADR.
  FFF9                          SECL    EQU STARTA+2    ; 0FFF9H SEKTORL[NGE
                                
  0007                          DRVS    EQU 07H         ; ANZAHL DER LAUFWERKE
  0200                          SECSIZE EQU 0200H       ; 512B  C=LOW , B=HIGH
                                
                                ;*********************************
                                ; EPROM ]BERTRAGEN IN RAM (F800H=
                                
                                ; KOPIERE NACH RAM LH BANK0 <32k
  03C5    21 0596               BIOS:   LD HL,START             ; PROG.ADR. QUELLE
  03C8    11 F814                       LD DE,B1                ; ZIEL RAM
  03CB    01 07EB                       LD BC,07EBH             ; PROG. LAENGE START(F814) - FFFFH 
  03CE    ED B0                         LDIR                    ; UEBERTRGEN NACH LOW BANK0
                                
                                ;-----------------------
                                ; IN BANK1 HIGH SCHREIBEN
  03D0    DB 1C                         IN A,(PIOA)             ; SRAM UMSCHALTEN AUF HH WRITE
  03D2    CB 87                         RES TAS,A
  03D4    CB EF                         SET TA16,A
  03D6    D3 1C                         OUT (PIOA),A            ; BANK1 HIGH WR EIN
                                
                                        ;KOPIERE VOM LL NACH RAM HH BANK1 <32K
  03D8    21 0596                       LD HL,START             ; PROG.ADR. QUELLE
  03DB    11 F814                       LD DE,B1                ; ZIEL RAM
  03DE    01 07EB                       LD BC,07EBH             ; PROG. L[NGE
  03E1    ED B0                         LDIR                    ; UEBERTRGEN NACH HIGH BANK1
                                
                                        ;--------------------------
                                        ; ZUR]CK NACH BANK0 LOW
                                        ; STACK AUF BANK1 HIGH SICHERN
                                        ; RUECKSPRUNGDATEN AUS HIGH INT.
                                
        MACRO-80 3.43   27-Jul-81       PAGE    1-16


  03E3    31 9000                       LD SP,9000H
  03E6    21 F83B                       LD HL,BOOT1
  03E9    E5                            PUSH HL         ; RETI RUECKSPRUNGADRESSE
  03EA    DD E5                         PUSH IX         ; INHALT RETTEN
  03EC    ED 73 FFA0                    LD (TSP),SP     ; RETI RUECKSPRUNGADRESSE BANK1 HH
  03F0    31 FFA0                       LD SP,TSP
                                        ;-------------
                                        ; AKTUELLE CPU, PIOA, PIOB, LATCH SICHERN
  03F3    F5                            PUSH AF
  03F4    DB 1C                         IN A,(PIOA)
  03F6    F5                            PUSH AF
                                        ;-------------
                                        ; KARTEN LATCH RETTEN
  03F7    6F                            LD L,A          ; ZUM ZURUECKSETZEN
  03F8    CB FF                         SET 7,A         ; SET EXTERN
  03FA    D3 1C                         OUT (PIOA),A
  03FC    DB F5                         IN A,(LATCH)    ; LETZTE KATRENNUMMER
  03FE    F5                            PUSH AF
  03FF    7D                            LD A,L
  0400    D3 1C                         OUT (PIOA),A
                                        ;-------------
  0402    DB 1E                         IN A,(PIOB)
  0404    F5                            PUSH AF
                                        ;--------------
  0405    C5                            PUSH BC
  0406    D5                            PUSH DE
  0407    E5                            PUSH HL
  0408    FD E5                         PUSH IY
  040A    08                            EX AF,AF'       ; AF TAUSCHEN
  040B    D9                            EXX             ; BC, DE, HL TAUSCHEN
  040C    F5                            PUSH AF
  040D    C5                            PUSH BC
  040E    D5                            PUSH DE
  040F    E5                            PUSH HL
                                
                                        ;---------------
                                        ; CTC 3 MIT INTERRUPT STARTEN
                                
  0410    F3                            DI
  0411    21 FD67                       LD HL,TASK
  0414    22 F806                       LD (0F806H),HL  ; INT ADRESSE FUER BANK1 HH
                                
  0417    3E 40                         LD A,EOFF       ; EPROM OFF, INTERN, BANK0 LL
  0419    D3 1C                         OUT (PIOA),A
                                
  041B    31 9000                       LD SP,9000H
  041E    22 F806                       LD (0F806H),HL  ; INT ADRESSE FUER BANK LL
                                
                                        ;-----------------
                                        ; CTC3 INTERRUPT INIT
                                
  0421    21 F800                       LD HL,0F800H
  0424    7C                            LD A,H
  0425    ED 47                         LD I,A
  0427    3E C7                         LD A,BAUD4
  0429    D3 13                         OUT (CTC3),A
        MACRO-80 3.43   27-Jul-81       PAGE    1-17


  042B    3E 0F                         LD A,TIME4
  042D    D3 13                         OUT (CTC3),A
  042F    7D                            LD A,L
  0430    D3 10                         OUT (CTC0),A
  0432    AF                            XOR A
  0433    CB F7                         SET ELATCH,A
  0435    D3 1C                         OUT (PIOA),A
  0437    C3 F83B                       JP BOOT1                ; START BOOT
                                
                                ;--------------------------
                                ; INT CTC3 * COUNT IN I/O SRAM
                                
  043A    DB 1E                 TASKEP: IN A,(PIOB)
  043C    F5                            PUSH AF
  043D    3E 3F                         LD A,3FH
  043F    D3 1E                         OUT (PIOB),A            ; I/O SRAM BANK SETZEN
  0441    DB 96                         IN A,(URCS+16H)
  0443    3D                            DEC A
  0444    28 04                         JR Z,TAS01
  0446    D3 96                         OUT (URCS+16H),A
  0448    18 2A                         JR TASK14
                                
                                        ;-------------------
                                        ; >1ms DANN AUSFUEHREN
                                
  044A    DB 97                 TAS01:  IN A,(URCS+17H)
  044C    D3 96                         OUT (URCS+16H),A        ; TIMER NEU STARTEN
  044E    C5                            PUSH BC
  044F    D5                            PUSH DE
  0450    E5                            PUSH HL
  0451    FD E5                         PUSH IY
  0453    08                            EX AF,AF'
  0454    D9                            EXX
  0455    F5                            PUSH AF
  0456    C5                            PUSH BC
  0457    D5                            PUSH DE
  0458    E5                            PUSH HL
                                        ;-------------
                                        ; BANK UNSCHALTEN 
  0459    DB 1C                         IN A,(PIOA)
  045B    CB 6F                         BIT TA16,A
  045D    20 04                         JR NZ,TAS12
  045F    CB EF                         SET TA16,A      ; -> BANK1
  0461    18 02                         JR TAS13
  0463    CB AF                 TAS12:  RES TA16,A      ; -> BANK0
  0465    CB 87                 TAS13:  RES TAS,A
  0467    D3 1C                         OUT (PIOA),A
                                        ;--------------
  0469    E1                            POP HL
  046A    D1                            POP DE
  046B    C1                            POP BC
  046C    F1                            POP AF
  046D    D9                            EXX
  046E    08                            EX AF,AF'
  046F    FD E1                         POP IY
  0471    E1                            POP HL
        MACRO-80 3.43   27-Jul-81       PAGE    1-18


  0472    D1                            POP DE
  0473    C1                            POP BC
  0474    F1                    TASK14: POP AF
  0475    D3 1E                         OUT (PIOB),A
  0477    C3 FD88                       JP TASK1
                                
                                ;--------------------------------
                                ; FDC STARTINITIALISIERUNG DD DRIVE A
                                ;------------------------
                                        ; FDC RESET HARDWAR
  047A    CD 0561               INITIA: CALL RY01               ; FDC HARTWARE RESET
  047D    06 0A                         LD B,0AH                ; 10*8=80 MAL FFH TAKTEN
  047F    DB 21                         IN A,(FDC+1)            ; ERST SD_CS AUF 1 SETZEN DISABLE
  0481    CB 47                         BIT 0,A                 ; MMC-KARTEN SELEKT
  0483    28 2E                         JR Z,SDERR
                                ;
                                ; SENDE MINDESTENS 74 CLOCK-SIGNALE
                                ;
  0485    3E FF                 SD_INI: LD A,0FFH
  0487    D3 21                         OUT (FDC+1),A           ; NUMBER OF DUMMY CLOCK
  0489    10 FA                         DJNZ SD_INI
                                
                                ;
                                ; SEND COMDO GO_IDLE_STATA
                                ;
  048B    01 0000                       LD BC,0000H
  048E    CD FB0B                       CALL SETTRK
  0491    CD FB1E                       CALL SETSEC
  0494    21 FDB2                       LD HL,SDRES             ; MMC-KARTE RESET GO_IDLE_STATA COMMAND
  0497    CD F9D3                       CALL COMUP              ; NUR COMMAND LADEN
  049A    CD F94C                       CALL COMMAND
  049D    21 FF33                       LD HL,STAT0
  04A0    CD FD53                       CALL TEXTOUT
  04A3    CD F96F                       CALL GETBYTE            ; MMC STATUS READ
  04A6    CD FCF5                       CALL STFDC              ; SEND DISPLAY
  04A9    21 FF4C                       LD HL,STAT0E
  04AC    CD FD53                       CALL TEXTOUT
  04AF    CB 47                         BIT 0,A
  04B1    20 08                         JR NZ,SDINI1            ; CHECK BIT 0= 1 ->
                                        ;--------
  04B3    21 FF02               SDERR:  LD HL,RESNEU
  04B6    CD FD53                       CALL TEXTOUT
  04B9    18 BF                         JR INITIA               ; INIT MMC NEW START
                                ;
                                ; SEND CMD1
                                ; CART FROM IDLE-MODE ON BETRIEBSMODE SET
                                ;
                                
  04BB    21 FF33               SDINI1: LD HL,STAT0
  04BE    CD FD53                       CALL TEXTOUT
  04C1    21 FDB8                       LD HL,SDCMD1    ; CMD1 KARTE READ X
  04C4    CD F9D3                       CALL COMUP      ; NUR COMMAND LADEN
  04C7    CD F94C                       CALL COMMAND
  04CA    CD F96F                       CALL GETBYTE
  04CD    CD FCF5                       CALL STFDC
  04D0    21 FF4C                       LD HL,STAT0E
        MACRO-80 3.43   27-Jul-81       PAGE    1-19


  04D3    CD FD53                       CALL TEXTOUT
  04D6    E6 FF                         AND 0FFH
  04D8    20 E1                         JR NZ,SDINI1    ; STATUS NOT 00 ->
                                ;
                                ; SEND CMD16 DATENBLOCK 512BYTE
                                ; SET BLOCKGOESSE AUF 512BYTE
                                ;
                                ;       LD HL,STAT0
                                ;       CALL TEXTOUT
  04DA    21 FDCA                       LD HL,SDBL
  04DD    CD F9D3                       CALL COMUP      ; NUR COMMAND LADEN
  04E0    CD F94C                       CALL COMMAND
  04E3    06 FF                         LD B,0FFH
  04E5    10 FE                         DJNZ $
  04E7    CD F96F                       CALL GETBYTE
  04EA    CD FCF5                       CALL STFDC
                                ;       LD HL,STAT0E
                                ;       CALL TEXTOUT
  04ED    E6 FF                         AND 0FFH
  04EF    20 C2                         JR NZ,SDERR
                                ;----------------------
  04F1    21 FF33                       LD HL,STAT0
  04F4    CD FD53                       CALL TEXTOUT
  04F7    21 FDBE                       LD HL,SDID
  04FA    CD F9D3                       CALL COMUP      ; NUR COMMAND LADEN
  04FD    CD F94C                       CALL COMMAND
  0500    06 FF                         LD B,0FFH
  0502    10 FE                         DJNZ $
  0504    CD F96F                       CALL GETBYTE
  0507    CD FCF5                       CALL STFDC
  050A    21 FF4C                       LD HL,STAT0E
  050D    CD FD53                       CALL TEXTOUT
  0510    E6 FF                         AND 0FFH
  0512    20 9F                         JR NZ,SDERR
                                ;---------------------------
                                ; KARTEN ID-NUMMER LESEN
                                
  0514    21 FF52                       LD HL,STAT3
  0517    CD FD53                       CALL TEXTOUT
  051A    06 14                         LD B,14H
  051C    CD F96F               SDRDID: CALL GETBYTE
  051F    CD FD28                       CALL HEX
  0522    10 F8                         DJNZ SDRDID
  0524    21 FF65                       LD HL,STAT3E
  0527    CD FD53                       CALL TEXTOUT
                                ;----------------------------
                                
  052A    21 FF33                       LD HL,STAT0
  052D    CD FD53                       CALL TEXTOUT
  0530    21 FDC4                       LD HL,SDCSD     ; MMC-KARTE SPEZIFISCHE DATEN
  0533    CD F9D3                       CALL COMUP
  0536    CD F94C                       CALL COMMAND
  0539    CD F96F                       CALL GETBYTE
  053C    CD FCF5                       CALL STFDC
  053F    21 FF4C                       LD HL,STAT0E
  0542    CD FD53                       CALL TEXTOUT
        MACRO-80 3.43   27-Jul-81       PAGE    1-20


  0545    CB 47                         BIT 0,A
  0547    C2 04B3                       JP NZ,SDERR
                                ;---------------------------
                                ; MMC-KARTE SPEZIFISCHE DATEN LESEN
                                
  054A    21 FF52                       LD HL,STAT3
  054D    CD FD53                       CALL TEXTOUT
  0550    06 14                         LD B,14H
  0552    CD F96F               SDCSD0: CALL GETBYTE
  0555    CD FD28                       CALL HEX
  0558    10 F8                         DJNZ SDCSD0
  055A    21 FF65                       LD HL,STAT3E
  055D    CD FD53                       CALL TEXTOUT
                                ;       CALL HOME0
  0560    C9                            RET
                                ;---------------------------
                                ;       FDC READY MASTE STATUS BIT 7
                                
  0561    F5                    RY01:   PUSH AF
  0562    3E 0F                         LD A,0FH
  0564    CD FCE1                       CALL FDCHRES
  0567    3E 1F                         LD A,1FH
  0569    CD 056E                       CALL PAUS
  056C    F1                            POP AF
  056D    C9                            RET
                                ;----------------------------------
                                ; PAUSE
                                
  056E    00                    PAUS:   NOP
  056F    C5                    F08FB:  PUSH BC
  0570    D5                            PUSH DE
  0571    F5                    PAUS01: PUSH AF
  0572    0E CF                         LD C,0CFH
  0574    06 40                 FDCP2:  LD B,40H
  0576    DB 13                 FDCP1:  IN A,(CTC3)
  0578    B9                            CP C
  0579    28 FB                         JR Z,FDCP1
  057B    4F                            LD C,A
  057C    10 F8                         DJNZ FDCP1
  057E    1D                            DEC E
  057F    C2 0574                       JP NZ,FDCP2
  0582    F1                            POP AF
  0583    3D                            DEC A
  0584    20 EB                         JR NZ,PAUS01
  0586    D1                            POP DE
  0587    C1                            POP BC
  0588    C9                            RET
                                ;------------------------------
                                ; STATUSTEXT IN A,(C) ALS BIN[R AUSGEBEN
                                
  0589    21 FED4               MSTAT:  LD HL,MSGTF        ; STATUSTEXT 1.H[LFTE        IN A,(C)           ; DANACH STATUS LESEN
  058C    CD FCF5                       CALL STFDC         ; AKKU IN BCD AUSGEBEN AB CURSOR
  058F    21 FEF3                       LD HL,MSGTE        ; STATUSTEST 2. H[LFTE
  0592    CD FD53                       CALL TEXTOUT       ; AUSGEBEN
  0595    C9                            RET
                                ;------------------------------
        MACRO-80 3.43   27-Jul-81       PAGE    1-21


                                
  0596                          START:
                                
                                .PHASE 0F814H
                                
                                        ;----------------------------------
                                        ; SPRUNGTABELLE F]R DISK-COMMAND
                                        ;----------------------------------
                                
  F814    C3 FA22               B1:     JP READ         ; F814H
  F817    C3 FAA3               B2:     JP WRITE        ; F817H
  F81A    C3 F972               B3:     JP HOME         ; F81AH
  F81D    C3 FC77               B4:     JP CONOUT       ; F81DH
  F820    C3 FC94               B5:     JP CONIN        ; F820H
  F823    C3 FCAE               B6:     JP CONST        ; F823H
  F826    C3 FC52               B7:     JP LIST         ; F826H
  F829    C3 FC4C               B8:     JP LISTST       ; F829H
  F82C    C3 FD66               B9:     JP LCDOUT       ; F82CH
  F82F    C3 FB10               B10:    JP SETDMA       ; F82FH
  F832    C3 FB0B               B11:    JP SETTRK       ; F832H
  F835    C3 FB1E               B12:    JP SETSEC       ; F835H
  F838    C3 FB06               B13:    JP SELDSK       ; F838H
                                
                                        ;----------------------------
                                
  F83B    F3                    BOOT1:  DI
  F83C    31 9000                       LD SP,09000H
  F83F    21 FDDC                       LD HL,MSGTS             ; TEXT
  F842    CD FD53                       CALL TEXTOUT            ; TEXT AUSGEBEN
  F845    21 0000                       LD HL,0000H             ; CLEAR I/O & DRIVE BYTES
  F848    22 0003                       LD (IOBYTE),HL
  F84B    CD 047A                       CALL INITIA
  F84E    38 EB                         JR C,BOOT1
                                
  F850    21 03B1                       LD HL,SDOK
  F853    CD FC05                       CALL IDERES
  F856    0E 01                         LD C,01H
  F858    06 00                         LD B,00H
  F85A    CD FB1E               BOOTN:  CALL SETSEC             ; START SEKTOR
  F85D    01 0200                       LD BC,SECSIZE      ; SEKTORL[NGE
  F860    ED 43 FFF9                    LD (SECL),BC
  F864    01 FFF0                       LD BC,FIRST     ;
  F867    CD FB10                       CALL SETDMA             ; ERSTE SPUR
  F86A    01 0000                       LD BC,0000H
  F86D    CD FB0B                       CALL SETTRK             ; ERSTER SEKTOR
  F870    CD FB06                       CALL SELDSK             ; AUS LAUFWERK A: SETZEN
  F873    ED 43 FFA4                    LD (TRACKL),BC
  F877    CD FA22                       CALL READ               ; TRK,SEK 0,1 LESEN =DISK DATEN
  F87A    38 BF                         JR C,BOOT1              ; FEHLER ->
  F87C    21 FF6B                       LD HL,CRLF
  F87F    CD FD53                       CALL TEXTOUT
                                ;_ TEST
  F882    3A FFB0                       LD A,(NBUF)
                                ;       CALL HEX
  F885    3A FFB1                       LD A,(NBUF+1)
                                ;       CALL HEX
        MACRO-80 3.43   27-Jul-81       PAGE    1-22


  F888    3A FFB2                       LD A,(NBUF+2)
                                ;       CALL HEX
  F88B    3A FFB3                       LD A,(NBUF+3)
                                ;       CALL HEX
  F88E    3A FFB4                       LD A,(NBUF+4)
                                ;       CALL HEX
  F891    3A FFB5                       LD A,(NBUF+5)
                                ;       CALL HEX
                                        ;-------------
                                ; STARTSEQUENZ VON KARTE GELADEN
                                ; FIRST:00, SA:02, SM:1F, DMA:00D4
                                ; ENA:FFF2, STARTA:00EA, SECL:0002
                                ;
  F894    21 FFF0               DBOOT:  LD HL,FIRST
  F897    06 0D                         LD B,0DH
  F899    7E                    DTEST:  LD A,(HL)
                                ;       CALL HEX
  F89A    23                            INC HL
                                ;       DJNZ DTEST
                                        ;-----------
  F89B    21 FF6B                       LD HL,CRLF
  F89E    CD FD53                       CALL TEXTOUT
  F8A1    2A FFF5                       LD HL,(ENA)        ; ENDADRESSE
  F8A4    ED 5B FFF3                    LD DE,(DMA)        ; ANFANGSADRESSE
  F8A8    ED 52                         SBC HL,DE           ; SPEICHERBEDARF IN HL
  F8AA    CA F916                       JP Z,NOSYS         ; AUSGANG OHNE SYSTEM
  F8AD    ED 5B FFF9                    LD DE,(SECL)       ; SEKTORL[NGE
  F8B1    ED 4B FFF3                    LD BC,(DMA)
  F8B5    CD FB10                       CALL SETDMA
  F8B8    01 0000                       LD BC,0000H             ; SEKTORENZ[HLER
  F8BB    CD FB0B                       CALL SETTRK
  F8BE    CD FB06                       CALL SELDSK
  F8C1    ED 52                 DIVI:   SBC HL,DE
  F8C3    04                            INC B               ; SEKTOR -> SPEICHERBEDARFSZ[HLER
  F8C4    38 04                         JR C,DIV
  F8C6    28 02                         JR Z,DIV
  F8C8    18 F7                         JR DIVI
                                        ;-------------
  F8CA    3A FFF1               DIV:    LD A,(SA)           ;SEKTOR VON BOOT DISK/MMC
  F8CD    57                            LD D,A
  F8CE    4A                    DB01:   LD C,D
  F8CF    CD FB15                       CALL SETSEC8        ; SET 8BIT LOW
  F8D2    C5                            PUSH BC
  F8D3    CD FA22                       CALL READ
  F8D6    DA F83B                       JP C,BOOT1          ; FEHLER -> NEUSTART
  F8D9    21 FF6B                       LD HL,CRLF
  F8DC    CD FD53                       CALL TEXTOUT
  F8DF    2A FFA6                       LD HL,(HSTDMA)
                                ;       JR DB04
                                ;----------
                                ; ZUM TEST AUSGABE  BOOTSEKTOREB
  F8E2    7C                            LD A,H          ; HIGH DMA ADR.
                                ;       CALL HEX
  F8E3    7E                            LD A,(HL)       ; INHALT DMA ADR.
                                ;       CALL HEX
  F8E4    7A                            LD A,D          ; SEKTOR LOW 8BIT
        MACRO-80 3.43   27-Jul-81       PAGE    1-23


                                ;       CALL HEX
                                ; MMC ADR. 32BIT SEC+TRK SHIFT 512
  F8E5    3A FFB1                       LD A,(NBUF+1)
                                ;       CALL HEX
  F8E8    3A FFB2                       LD A,(NBUF+2)
                                ;       CALL HEX
  F8EB    3A FFB3                       LD A,(NBUF+3)
                                ;       CALL HEX
  F8EE    3A FFB4                       LD A,(NBUF+4)
                                ;       CALL HEX
                                        ;-----------
  F8F1    ED 4B FFF9            DB04:   LD BC,(SECL)
  F8F5    09                            ADD HL,BC           ; ADR. AKTUELL
  F8F6    22 FFA6                       LD (HSTDMA),HL
  F8F9    C1                            POP BC
                                ;       JR NZ,DBOOT
  F8FA    05                            DEC B
  F8FB    28 22                         JR Z,DB02          ; ERFOLGREICH SYSTEM GELADEN
  F8FD    14                            INC D
  F8FE    3A FFF2                       LD A,(SM)
  F901    BA                            CP D               ; SPURENDE
  F902    38 02                         JR C,DB03
  F904    18 C8                         JR DB01
                                        ;-------------
  F906    16 01                 DB03:   LD      D,1
  F908    C5                            PUSH    BC
  F909    ED 4B FFAA                    LD      BC,(HSTTRK)
  F90D    0C                            INC     C
  F90E    06 00                         LD      B,0
  F910    CD FB0B                       CALL    SETTRK
  F913    C1                            POP     BC
  F914    18 B8                         JR      DB01
                                        ;-------------
  F916    21 FF19               NOSYS:  LD HL,SYSERR
  F919    CD FD53                       CALL TEXTOUT
  F91C    C3 F83B                       JP BOOT1           ; FEHLER -> NEUSTART
                                
  F91F    21 FF6B               DB02:   LD HL,CRLF
  F922    CD FD53                       CALL TEXTOUT
  F925    CD FCD0                       CALL MEPROM             ; EPROM AUS
  F928    2A FFF7                       LD HL,(STARTA)
  F92B    E9                            JP (HL)
                                ;--------------------------------
                                ;_ TEST
  F92C    CD FD28               GROUP:  CALL HEX
  F92F    F5                            PUSH AF
  F930    78                            LD A,B
  F931    CD FD28                       CALL HEX
  F934    79                            LD A,C
  F935    CD FD28                       CALL HEX
  F938    7A                            LD A,D
  F939    CD FD28                       CALL HEX
  F93C    7B                            LD A,E
  F93D    CD FD28                       CALL HEX
  F940    0E 0A                         LD C,0AH
  F942    CD FC77                       CALL CONOUT
        MACRO-80 3.43   27-Jul-81       PAGE    1-24


  F945    0E 0D                         LD C,0DH
  F947    CD FC77                       CALL CONOUT
  F94A    F1                            POP AF
  F94B    C9                            RET
                                ;--------------------------------
                                ; **** COMMAND ****
                                ; COMMANDO AUF TABELLE IN HL AUSGEBEN
                                ;
  F94C    C5                    COMMAND:PUSH BC
  F94D    E5                            PUSH HL
  F94E    DB 20                         IN A,(FDC)
  F950    CD F961                       CALL CARDDELAY          ;SD-CS AUF 0 SETZEN
  F953    21 FFB0                       LD HL,NBUF
  F956    06 06                         LD B,06H
  F958    7E                    SDCOM:  LD A,(HL)          ; KARTEN ERKENNEN
  F959    D3 20                         OUT (FDC),A             ; WAIT IN HARDWARE
  F95B    23                            INC HL
  F95C    00                            NOP
  F95D    10 F9                         DJNZ SDCOM
  F95F    E1                            POP HL
  F960    C1                            POP BC
                                        ;----------------
  F961    3E FF                 CARDDELAY: LD A,0FFH
  F963    D3 20                 SENDBYTE: OUT (FDC),A
                                
  F965    C9                            RET
                                        ;-----------------
  F966    F5                    SD_STATUS: PUSH AF
  F967    DB 20                 SS1:    IN A,(FDC)
  F969    FE 00                         CP 0            ;BIT 0,A
  F96B    20 FA                         JR NZ,SS1
  F96D    F1                            POP AF
  F96E    C9                            RET
                                        ;-----------------
  F96F    DB 20                 GETBYTE: IN A,(FDC)
  F971    C9                            RET
                                ;--------------------------------
                                ;        *** HOME ***
                                ;  KOPF AUF SPUR NULL MIT VERIFY
                                ;
  F972    3A FFAD               HOME:   LD A,(DRIVE)
  F975    E6 0F                         AND 0FH             ; NUR DRIVE SELEKT
  F977    FE 00                         CP 0
  F979    20 1B                         JR NZ,HOMHD
  F97B    18 19                         JR HOMHD
  F97D    C5                            PUSH BC
  F97E    D5                            PUSH DE
  F97F    E5                            PUSH HL
  F980    01 0000                       LD BC,0000H
  F983    CD FB0B                       CALL SETTRK
  F986    01 0000                       LD BC,0000H
  F989    CD FB1E                       CALL SETSEC
  F98C    AF                            XOR A
  F98D    32 FFA4                       LD (TRACKL),A
  F990    32 FFA5                       LD (TRACKH),A
  F993    E1                            POP HL
        MACRO-80 3.43   27-Jul-81       PAGE    1-25


  F994    D1                            POP DE
  F995    C1                            POP BC
  F996    AF                    HOMHD:  XOR A
  F997    C9                            RET
                                ;--------------------------------
                                ; **** MOVE HEAD ****
                                ; KOPFBEWEGUNG HOMEBZW.AUF AUSGEW. SPUR
                                ;
  F998    C5                    HOME0:  PUSH BC
  F999    E5                            PUSH HL
  F99A    01 0000                       LD BC,0000H
                                
  F99D    21 FDB8               TI1:    LD HL,SDCMD1       ; CMD1 KARTE READY?
  F9A0    CD F9D3                       CALL COMUP         ; IN BUFFER LADEN
  F9A3    CD F94C                       CALL COMMAND
  F9A6    DB 20                         IN A,(FDC)
  F9A8    32 FFAF                       LD (STATUS),A
  F9AB    CB 47                         BIT 0,A
  F9AD    28 20                         JR Z,HOK0         ; PR]FE OB SD-KARTE READY
  F9AF    10 EC                         DJNZ TI1
  F9B1    21 FDB2                       LD HL,SDRES        ;MMC-KARTE RESET COMMAND
  F9B4    CD F9D3                       CALL COMUP
  F9B7    CD F94C                       CALL COMMAND
  F9BA    06 0F                         LD B,0FH           ; PAUSE ZEIT
  F9BC    10 FE                         DJNZ $
  F9BE    DB 20                         IN A,(FDC)
  F9C0    CB 47                         BIT 0,A
  F9C2    28 0B                         JR Z,HOK0
  F9C4    0D                            DEC C
  F9C5    28 02                         JR Z,HOKE0
  F9C7    18 D4                         JR TI1
                                
  F9C9    E1                    HOKE0:  POP HL
  F9CA    C1                            POP BC
  F9CB    AF                    HOKE:   XOR A
  F9CC    3C                            INC A               ; DAMIT Z-FLAG =1
  F9CD    37                            SCF                     ; SET C-FLAG =1 FEHLER
  F9CE    C9                            RET
                                
  F9CF    E1                    HOK0:   POP     HL
  F9D0    C1                            POP     BC
  F9D1    AF                    HOK:    XOR     A               ; L\SCHE Z, C-FLAG =0
  F9D2    C9                            RET
                                ;-------------------------------
                                ; EPROM AUS?  COMMAND AUS (HL) -> (DE) NBUF LADEN
                                ; ??? DIREKT AUS COMMAND LADEN ???
                                
  F9D3    D5                    COMUP:  PUSH DE
  F9D4    C5                            PUSH BC
  F9D5    11 FFB0                       LD DE,NBUF
  F9D8    01 0006                       LD BC,0006H
  F9DB    ED B0                         LDIR
  F9DD    C1                            POP BC
  F9DE    D1                            POP DE
  F9DF    C9                            RET
                                
        MACRO-80 3.43   27-Jul-81       PAGE    1-26


                                ;--------------------------------
                                ; **** SEC ****
                                
  F9E0    EB                    SECTRAN:EX     DE,HL
  F9E1    09                            ADD     HL,BC
  F9E2    6E                            LD      L,(HL)
  F9E3    26 00                         LD      H,0
  F9E5    C9                            RET
                                
                                ;--------------------------------
                                ; ***** READ *****
                                ; SEKTOR LESEN
                                ; IDE HD
                                
  F9E6                          READHST:
  F9E6    DB 1C                         IN A,(PIOA)
  F9E8    CB FF                         SET 7,A         ; BIT 7 EXT/INT
  F9EA    D3 1C                         OUT (PIOA),A    ; EXTERN UNSCHALTEN
  F9EC    C5                            PUSH BC
  F9ED    D5                            PUSH DE
  F9EE    ED 4B FFAA                    LD BC,(HSTTRK)
  F9F2    ED 5B FFA8                    LD DE,(HSTSEC)          ; B= HS3-HS0 LOGICAL HEAD SELECT BITS
  F9F6    CD FB97                       CALL IDE_SET_LBA        ; SET UP TASK FILE
  F9F9    D1                            POP DE
  F9FA    C1                            POP BC
  F9FB    3E 20                         LD A,CMD_READSEC
  F9FD    D3 FF                         OUT (IDECMD),A
  F9FF    CD FBC4                       CALL WAITDRQ
  FA02    38 15                         JR C,READH2
  FA04    2A FFA6                       LD HL,(HSTDMA)
  FA07    0E F8                         LD C,IDEDAT
  FA09    06 00                         LD B,0          ; 1x256BYTE
  FA0B    ED B2                         INIR            ; 8BIT 256 BYTE LESEN VON HD
  FA0D    06 00                         LD B,0          ; AGAIN 2x256BYTE = 512BYTE
  FA0F    ED B2                         INIR            ; 8BIT 256 BYTE LESEN VON HD
                                
  FA11    F1                    CHKERR: POP AF          ; PIOA HOLEN
  FA12    E1                            POP HL          ; ZURUECK AUS READ: PUSH
  FA13    D1                            POP DE
  FA14    C1                            POP BC
  FA15    F5                            PUSH AF         ; PIOA NOCH MAL RETTEN
  FA16    C3 FBE5                       JP WAITRDY
                                        ;---------------
  FA19    F1                    READH2: POP AF
  FA1A    D3 1C                         OUT (PIOA),A    ; PIOA AUF ZURUECKSET.
  FA1C    E1                            POP HL          ; ZURUECK AUS READ: PUSH
  FA1D    D1                            POP DE
  FA1E    C1                            POP BC
  FA1F    C3 F9CB                       JP HOKE         ; AUSGANG ERROR
                                
                                        ;-----------------
                                        ; MMC-KARTE READ
                                
  FA22    C5                    READ:   PUSH BC
  FA23    D5                            PUSH DE
  FA24    E5                            PUSH HL
        MACRO-80 3.43   27-Jul-81       PAGE    1-27


  FA25    DB 1C                         IN A,(PIOA)
  FA27    F5                            PUSH AF
  FA28    CD FC19                       CALL SELDR
  FA2B    3A FFAD                       LD A,(DRIVE)
  FA2E    CB 7F                         BIT 7,A
  FA30    20 B4                         JR NZ,READHST   ; -> ZU IDE FESTPLATTE
                                        ;----------------------
                                        ; MMC-KARTE
  FA32    DB 1C                         IN A,(PIOA)
  FA34    CB BF                         RES 7,A
  FA36    D3 1C                         OUT (PIOA),A
  FA38    21 FDD6                       LD  HL,SDREAD               ;MMC-KARTE READCOMMAND LESEN
  FA3B    CD F9D3                       CALL COMUP
  FA3E    CD FB5E                       CALL RWSETUP
  FA41    CD FB23                       CALL SL32               ; SHIFT 9BIT LINKS =512BIT SECTOR
  FA44    CD F94C                       CALL COMMAND
  FA47    DB 20                         IN A,(FDC)
  FA49    FE 00                         CP 0
  FA4B    28 02                         JR Z,RD01
  FA4D    18 CA                 RD00:   JR READH2
                                
                                ;-------------------------
                                ;  MMC-KARTE 512 BYTE DATEN LESEN
                                
  FA4F    DB 20                 RD01:   IN A,(FDC)
  FA51    FE FE                         CP 0FEH
  FA53    20 FA                         JR NZ,RD01
  FA55    2A FFA6                       LD HL,(HSTDMA)
  FA58    ED 4B FFF9                    LD BC,(SECL)
  FA5C    DB 20                 SDRD02: IN A,(FDC)
  FA5E    77                            LD (HL),A
  FA5F    23                            INC HL
  FA60    0D                            DEC C
  FA61    20 F9                         JR NZ,SDRD02
  FA63    10 F7                         DJNZ SDRD02
  FA65    CD F961                       CALL CARDDELAY
  FA68    CD F961                       CALL CARDDELAY
                                        ;----------------
  FA6B    F1                    SDRD03: POP AF
  FA6C    D3 1C                         OUT (PIOA),A
  FA6E    E1                            POP HL
  FA6F    D1                            POP DE
  FA70    C1                            POP BC
  FA71    C3 F9D1                       JP HOK
                                
                                ;------------------------
                                ; **** WRITE ****
                                
                                        ;IDE HD
  FA74                          WRITEHST:
  FA74    DB 1C                         IN A,(PIOA)
  FA76    CB FF                         SET 7,A         ; BIT 7 EXT/INT
  FA78    D3 1C                         OUT (PIOA),A    ; TASK UNSCHALTEN
  FA7A    C5                            PUSH BC
  FA7B    D5                            PUSH DE
  FA7C    ED 4B FFAA                    LD BC,(HSTTRK)
        MACRO-80 3.43   27-Jul-81       PAGE    1-28


  FA80    ED 5B FFA8                    LD DE,(HSTSEC)          ; B= HS3-HS0 LOGICAL HEAD SELECT BITS
  FA84    CD FB97                       CALL IDE_SET_LBA        ; SET UP TASK FILE
  FA87    D1                            POP DE
  FA88    C1                            POP BC
  FA89    3E 30                         LD A,CMD_WRITESEC
  FA8B    D3 FF                         OUT (IDECMD),A
  FA8D    CD FBC4                       CALL WAITDRQ
  FA90    DA FA19                       JP C,READH2
  FA93    2A FFA6                       LD HL,(HSTDMA)
  FA96    0E F8                         LD C,IDEDAT
  FA98    06 00                         LD B,0          ; 1x256BYTE
  FA9A    ED B3                         OTIR            ; 8BIT 256 BYTE SCHREIBEN VON SRAM
  FA9C    06 00                         LD B,0          ; AGAIN 2x256BYTE = 512BYTE
  FA9E    ED B3                         OTIR
  FAA0    C3 FA11                       JP CHKERR
                                        ;----------------------
                                        ; MMC-KARTE
  FAA3    C5                    WRITE:  PUSH BC
  FAA4    D5                            PUSH DE
  FAA5    E5                            PUSH HL
  FAA6    DB 1C                         IN A,(PIOA)
  FAA8    F5                            PUSH AF
  FAA9    CD FC19                       CALL SELDR
  FAAC    3A FFAD                       LD A,(DRIVE)
  FAAF    CB 7F                         BIT 7,A
  FAB1    20 C1                         JR NZ,WRITEHST
                                        ;----------------
  FAB3    DB 1C                         IN A,(PIOA)
  FAB5    CB BF                         RES 7,A
  FAB7    D3 1C                         OUT (PIOA),A
                                ;       CALL SELTR
                                ;       JR C,WR00
  FAB9    21 FDD0                       LD HL,SDWRITE           ;MMC-KARTE DATEN LEDEN
  FABC    CD F9D3                       CALL COMUP
  FABF    CD FB5E                       CALL RWSETUP            ;STARTADRESSE VORBEREITEN
  FAC2    CD FB23                       CALL SL32
  FAC5    CD F94C                       CALL COMMAND
  FAC8    DB 20                         IN A,(FDC)
  FACA    FE 00                         CP 0
  FACC    28 03                         JR Z,WR01
  FACE    C3 FA19               WR00:   JP READH2
                                
                                ;-------------------------
                                ;  MMC-KARTE 512 BYTE DATEN SCHREIBEN
                                
  FAD1    CD F961               WR01:   CALL CARDDELAY
  FAD4    CD F961                       CALL CARDDELAY         ; AM ENDE 2 BYTE OHNE BEDEUTUNG
  FAD7    3E FE                         LD A,0FEH               ; START BYTE WRITE
  FAD9    CD F963                       CALL SENDBYTE
                                        ;--------------
  FADC    2A FFA6                       LD HL,(HSTDMA)
  FADF    ED 4B FFF9                    LD BC,(SECL)
  FAE3    7E                    SDWR01: LD A,(HL)
  FAE4    D3 20                         OUT (FDC),A
  FAE6    23                            INC HL
  FAE7    0D                            DEC C
        MACRO-80 3.43   27-Jul-81       PAGE    1-29


  FAE8    20 F9                         JR NZ,SDWR01
  FAEA    10 F7                         DJNZ SDWR01
  FAEC    CD F961                       CALL CARDDELAY
  FAEF    CD F961                       CALL CARDDELAY         ; AM ENDE 2 BYTE OHNE BEDEUTUNG
  FAF2    DB 20                 SDWR02: IN A,(FDC)
  FAF4    E6 1F                         AND 1FH
  FAF6    FE 05                         CP 05H
  FAF8    20 D4                         JR NZ,WR00         ; FEHLER
  FAFA    CD F961               SDWR03: CALL CARDDELAY
  FAFD    DB 20                         IN A,(FDC)
  FAFF    FE FF                         CP 0FFH
  FB01    20 F7                         JR NZ,SDWR03
  FB03    C3 FA6B                       JP SDRD03               ; ENDE
                                
                                ;-------------------------------
                                ; ***** SETDSKL *****
                                ; EINGANG C=LAUFWERKNUMMER
                                ; AUSGANG (NDRIVE)=LAUFWERKNUMMER
                                
  FB06    79                    SELDSK: LD A,C
  FB07    32 FFAC                       LD (HSTDSK),A      ;PHYSIK.NUMMER
  FB0A    C9                            RET
                                ;--------------------------------
                                ; NEUER TRACK
                                
  FB0B    ED 43 FFAA            SETTRK: LD      (HSTTRK),BC
  FB0F    C9                            RET
                                ;--------------------------------
                                ;  SETZE DMA
                                
  FB10    ED 43 FFA6            SETDMA: LD      (HSTDMA),BC
  FB14    C9                            RET
                                ;------------------------------
                                ; SEKTORNUMMER SETZEN
                                
  FB15    C5                    SETSEC8: PUSH BC
  FB16    06 00                         LD B,0          ; HEAD SELECT
  FB18    ED 43 FFA8                    LD (HSTSEC),BC
  FB1C    C1                            POP BC
  FB1D    C9                            RET
                                ;---------------------------
                                ; C= SECTOR, B= HEAD SELECT
                                
  FB1E    ED 43 FFA8            SETSEC: LD (HSTSEC),BC
  FB22    C9                            RET
                                ;-------------------------------
                                ; READ/WRITE SETUP ROUTINE
                                ; CREATES AN MMC COMPATIBLE BUFFER ADDRESS FOR THE TRACK AND
                                ; SECTOR NUMBER PASSEG FROM CP/M
                                ;--------------------------------
                                ; ADRESSE >512 MMC BLOCK 9BIT SHIFT BERECHNEN
                                
  FB23    DD E5                 SL32:   PUSH IX
  FB25    C5                            PUSH BC
  FB26    D5                            PUSH DE
  FB27    E5                            PUSH HL
        MACRO-80 3.43   27-Jul-81       PAGE    1-30


  FB28    06 09                         LD B,09H        ; SHIFT 32 BIT
  FB2A    DD 21 FFB0                    LD IX,NBUF
  FB2E    DD CB 01 26           SL321:  SLA (IX+1)
  FB32    DD CB 02 26                   SLA (IX+2)
  FB36    38 02                         JR C,SL01
  FB38    18 04                         JR SL322
  FB3A    DD CB 01 C6           SL01:   SET 0,(IX+1)
  FB3E    DD CB 03 26           SL322:  SLA (IX+3)
  FB42    38 02                         JR C,SL02
  FB44    18 04                         JR SL323
  FB46    DD CB 02 C6           SL02:   SET 0,(IX+2)
  FB4A    DD CB 04 26           SL323:  SLA (IX+4)
  FB4E    38 02                         JR C,SL03
  FB50    18 04                         JR SL324
  FB52    DD CB 03 C6           SL03:   SET 0,(IX+3)
  FB56    10 D6                 SL324:  DJNZ SL321
  FB58    E1                            POP HL
  FB59    D1                            POP DE
  FB5A    C1                            POP BC
  FB5B    DD E1                         POP IX
  FB5D    C9                            RET
                                ;----------------------------------
                                ; 3 BIT SHIFT LEFT. (=8D)
                                ; ENTRY: N/A
                                ; EXIT:  N/A
                                ; DESTROYS: AF, B, IX
                                
  FB5E                          RWSETUP:
  FB5E    DD E5                         PUSH IX
  FB60    C5                            PUSH BC
  FB61    D5                            PUSH DE
  FB62    E5                            PUSH HL
  FB63    01 0000                       LD BC,0000H
  FB66    2A FFAA                       LD HL,(HSTTRK)
  FB69    3A FFF2                       LD A,(SM)       ; ZUM SHIF ZUBSTIMMEN
  FB6C    B7                            OR A
  FB6D    1F                    RW02:   RRA             ; A * FAKTOR HL*2 RECHTS
  FB6E    B7                            OR A
  FB6F    28 06                         JR Z,RW03
  FB71    29                            ADD HL,HL       ; *2 SHIFT LINKS
  FB72    DC FB95                       CALL C,RW01
  FB75    18 F6                         JR RW02
                                        ;-----------
  FB77    ED 5B FFA8            RW03:   LD DE,(HSTSEC)
  FB7B    19                            ADD HL,DE       ; ADD TRACK + SECTOR
  FB7C    DC FB95                       CALL C,RW01
                                        ;----------------
                                        ; FUER IDE HDD
  FB7F    DD 21 FFB0                    LD IX,NBUF      ; 4 BYTE OF MEMORY
                                        ; KOEPFE IN B VON SECTOR NOCH SELECT = AND 7FH
                                        ; BC FUER GROESSEREN SPEICHER
  FB83    DD 70 01                      LD (IX+1),B
  FB86    DD 71 02                      LD (IX+2),C
  FB89    DD 74 03                      LD (IX+3),H
  FB8C    DD 75 04                      LD (IX+4),L
  FB8F    E1                            POP HL
        MACRO-80 3.43   27-Jul-81       PAGE    1-31


  FB90    D1                            POP DE
  FB91    C1                            POP BC
  FB92    DD E1                         POP IX
  FB94    C9                            RET
  FB95    03                    RW01:   INC BC          ; BEI UEBERLAUF
  FB96    C9                            RET
                                
                                ;-------------------------------
                                ; ### IDE ROUTINES ###
                                ;-------------------------------
                                ; SET SEKTOR COUNT AND LBA REGISTER OF THE DRIVE.
                                ; REGISTER BC = TRACK AND DE=SECTOR  CONTAIN THE SECTOR ADDRESS
                                ; (LBA 3, 2, 1 AND 0).
                                
  FB97                          IDE_SET_LBA:
  FB97    DB FF                         IN A,(IDESTAT)
  FB99    17                            RLA
  FB9A    38 FB                         JR C,IDE_SET_LBA
                                        ;-------
  FB9C    F5                            PUSH AF
  FB9D    18 05                         JR IDE_SET01
  FB9F    3E 49                         LD A,'I'
  FBA1    CD F92C                       CALL GROUP
                                
  FBA4                          IDE_SET01:
  FBA4    3E 01                         LD A,1
  FBA6    D3 FA                         OUT (IDESCNT),A
  FBA8    78                            LD A,B
  FBA9    D3 FD                         OUT (IDECHI),A          ; TRACK HIGH
  FBAB    79                            LD A,C
  FBAC    D3 FC                         OUT (IDECLO),A          ; TRACK LOW
  FBAE    7B                            LD A,E
  FBAF    D3 FB                         OUT (IDESNUM),A         ; SECTOR
                                ;       LD A,D
                                ;       AND 0FH
                                ;       LD D,A
  FBB1    3A FFAD                       LD A,(DRIVE)
  FBB4    E6 0F                         AND 0FH         ; HS0 - HS3 SELECT
  FBB6    3D                            DEC A
                                ;       OR D            ; LBA + HEAD
  FBB7    57                            LD D,A          ; 4BIT LOW
  FBB8    3A FFAD                       LD A,(DRIVE)
  FBBB    E6 F0                         AND 0F0H        ; LBA, SLAVE/MASTER
  FBBD    B2                            OR D            ; 4BIT HIGH
  FBBE    CB FF                         SET 7,A
  FBC0    D3 FE                         OUT (IDESDH),A
  FBC2    F1                            POP AF
  FBC3    C9                            RET
                                ;------------------------------
                                ; WAIT READY FOR DATA
                                ; BIT 3 IS SET WHEN IT IS
                                
  FBC4                          WAITDRQ:
  FBC4    0E C8                         LD C,200
  FBC6    06 C8                         LD B,200
  FBC8    AF                            XOR A           ; CARRY  C= 0
        MACRO-80 3.43   27-Jul-81       PAGE    1-32


  FBC9    DB FF                 WAITDR1:IN A,(IDECMD)
  FBCB    CB 5F                         BIT 3,A
  FBCD    C0                            RET NZ          ;,WAITEND
                                ;
                                ;
  FBCE    10 F9                         DJNZ WAITDR1
  FBD0    0D                            DEC C
  FBD1    20 F6                         JR NZ,WAITDR1
  FBD3    37                            SCF             ; CARRY C=1
  FBD4    C9                            RET
                                ;------------------------------
                                ; WAIT FOR THE CONTROLLER TO NOT BE BUSY WITH A COMMAND
                                ; IF BIT 7 IS SET, THE CONTROLLER IS BUSY
                                
  FBD5                          WAITBSY:
  FBD5    0E C8                         LD C,200        ; DELAY VALUE FOR MILISECONDS
  FBD7    06 C8                         LD B,200                ; TENTHS OF SECONDS
  FBD9    DB FF                         WAITBS1:IN A,(IDECMD)
  FBDB    CB 7F                         BIT 7,A         ; BUSY BIT SET
  FBDD    C8                            RET Z           ; NOT BUSY -> JUMP ON OUT
  FBDE    10 F9                         DJNZ WAITBS1
  FBE0    0D                            DEC C
  FBE1    20 F6                         JR NZ,WAITBS1
  FBE3    0C                            INC C           ; Z=1
  FBE4    C9                            RET
                                ;------------------------------
                                ; WAIT FOR THE CONTROLLER TO BE RADY FOR A COMMAND
                                ; BIT 6 IS SET WHEN THE DRIVE IS READY
                                
  FBE5    CD FBD5               WAITRDY:CALL WAITBSY
  FBE8    20 0F                         JR NZ,WAITERR
  FBEA    0E C8                         LD C,200        ;DELAY VALUE FOR MILISECONDS
  FBEC    06 C8                         LD B,200                ; TENTHS OF SECONDS
  FBEE    DB FF                 WAITRD1:IN A,(IDECMD)
  FBF0    CB 77                         BIT 6,A
  FBF2    20 0B                         JR NZ,WAITEND
  FBF4    10 F8                         DJNZ WAITRD1
  FBF6    0D                            DEC C
  FBF7    20 F5                         JR NZ,WAITRD1
                                        ;------------
  FBF9                          WAITERR:
  FBF9    F1                            POP AF
  FBFA    D3 1C                         OUT (PIOA),A
  FBFC    C3 F9CB                       JP HOKE         ; AUSGANG ERROR
                                        ;------------
  FBFF                          WAITEND:
  FBFF    F1                            POP AF
  FC00    D3 1C                         OUT (PIOA),A
  FC02    C3 F9D1                       JP HOK
                                
                                ;-------------------------------
                                ; IDE-FESTPLATTE RESET
                                
  FC05    CD FC0A               IDERES: CALL IDERES1
  FC08    18 CB                         JR WAITBSY
                                
        MACRO-80 3.43   27-Jul-81       PAGE    1-33


  FC0A    C5                    IDERES1:PUSH BC
  FC0B    3E 06                         LD A,06
  FC0D    D3 F6                         OUT (IDEDOR),A
  FC0F    06 00                         LD B,0
  FC11    10 FE                         DJNZ $
  FC13    3E 02                         LD A,02
  FC15    D3 F6                         OUT (IDEDOR),A
  FC17    C1                            POP BC
  FC18    C9                            RET
                                
                                ;-------------------------------
                                ;  LAUFWERK FESTLEGEN
                                
  FC19    D5                    SELDR:  PUSH    DE
  FC1A    E5                            PUSH    HL
  FC1B    21 FFAC                       LD      HL,HSTDSK       ; NEW DRIVE
  FC1E    3A FFAD                       LD      A,(DRIVE)       ; DRIVE CURRENT
  FC21    E6 0F                         AND     0FH
  FC23    57                            LD      D,A             ; MAX 16 DRIVE
  FC24    7E                            LD      A,(HL)          ; CP/M DRIVE
  FC25    E6 0F                         AND     0FH
  FC27    5F                            LD      E,A
  FC28    BA                            CP      D
  FC29    28 1E                         JR      Z,SELRET        ; DRIVE SCHON SELECT
  FC2B    16 00                         LD      D,0
  FC2D    21 FDAA                       LD      HL,TABLE
  FC30    19                            ADD     HL,DE           ; DRIVE SELECT
  FC31    7E                            LD      A,(HL)
  FC32    E6 F0                         AND 0F0H
  FC34    B3                            OR E                    ; IN E = DRIVE CP/M
  FC35    32 FFAD                       LD      (DRIVE),A       ; NEW DRIVE SET LBA, SLAVE/MASTER
  FC38    E6 80                         AND     80H             ; SET = EXTERN BUS
  FC3A    57                            LD      D,A
  FC3B    DB 1C                         IN      A,(PIOA)
  FC3D    CB BF                         RES     7,A             ; BIT 7 EXT/INT
  FC3F    B2                            OR      D
  FC40    D3 1C                         OUT     (PIOA),A        ; TASK UNSCHALTEN
  FC42    E6 80                         AND     80H
  FC44    28 03                         JR      Z,SELRET
  FC46    CD FC0A                       CALL    IDERES1         ; DRIVE EXTERN RESET
  FC49    E1                    SELRET: POP     HL
  FC4A    D1                            POP     DE
  FC4B    C9                            RET
                                
                                ;----------------
                                ; ZEICHEN IN C DRUCKEN
                                
  FC4C    0E 24                 LISTST: LD C,'$'
  FC4E    CD FC77                       CALL CONOUT
  FC51    C9                            RET  ;?
  FC52    E5                            LIST:   PUSH HL
  FC53    DD E5                         PUSH IX
  FC55    DD 21 0000                    LD IX,0
  FC59    DD 39                         ADD IX,SP
  FC5B    31 EA00                       LD SP,0EA00H            ; NEUER STACK >8000
  FC5E    DD E5                         PUSH IX
        MACRO-80 3.43   27-Jul-81       PAGE    1-34


  FC60    DB 1C                         IN A,(PIOA)
  FC62    F5                            PUSH AF
  FC63    CB B7                         RES ELATCH,A            ; EPROM EIN
  FC65    D3 1C                         OUT (PIOA),A
  FC67    D5                            PUSH DE
  FC68    59                            LD E,C                  ; ZEICHEN C NACH E RETTEN
  FC69    CD 00C7                       CALL PRINT              ; ZEICHEN IN E AUSGEBEN
  FC6C    D1                            POP DE
  FC6D    20 57                         JR NZ,CONST0
  FC6F    F1                            POP AF
  FC70    CB F7                         SET ELATCH,A            ; EPROM SICHER AUS
  FC72    D3 1C                         OUT (PIOA),A
  FC74    C3 0000                       JP 0H                   ; WARMSTART
                                ;----------------
                                ; ZEICHEN IN C AUSGEBEN
                                
  FC77    E5                    CONOUT: PUSH HL
  FC78    DD E5                         PUSH IX
  FC7A    DD 21 0000                    LD IX,0
  FC7E    DD 39                         ADD IX,SP
  FC80    31 EA00                       LD SP,0EA00H            ; NEUER STACK >8000
  FC83    DD E5                         PUSH IX
  FC85    DB 1C                         IN A,(PIOA)
  FC87    F5                            PUSH AF
  FC88    CB B7                         RES ELATCH,A            ; EPROM EIN
  FC8A    D3 1C                         OUT (PIOA),A
  FC8C    D5                            PUSH DE
  FC8D    59                            LD E,C                  ; ZEICHEN C NACH E RETTEN
  FC8E    CD 004C                       CALL OUT0               ; ZEICHEN IN E AUSGEBEN
  FC91    D1                            POP DE
  FC92    18 32                         JR CONST0
                                ;----------------
                                ; INPUT NEUES ZEICHEN
                                
  FC94    E5                    CONIN:  PUSH HL
  FC95    DD E5                         PUSH IX
  FC97    DD 21 0000                    LD IX,00
  FC9B    DD 39                         ADD IX,SP
  FC9D    31 EA00                       LD SP,0EA00H    ; NEUER STACK >8000
  FCA0    DD E5                         PUSH IX
  FCA2    DB 1C                         IN A,(PIOA)
  FCA4    F5                            PUSH AF
  FCA5    CB B7                         RES ELATCH,A            ; EPROM EIN
  FCA7    D3 1C                         OUT (PIOA),A
  FCA9    CD 006B                       CALL INP0               ; ZEICHEN IN C EINLESEN
  FCAC    18 18                         JR CONST0
                                
                                ;----------------
                                ; PRUEFE OB TASTE GEDRUECKT WURDE
                                
  FCAE    E5                    CONST:  PUSH HL
  FCAF    DD E5                         PUSH IX
  FCB1    DD 21 0000                    LD IX,00
  FCB5    DD 39                         ADD IX,SP
  FCB7    31 EA00                       LD SP,0EA00H    ; NEUER STACK >8000
  FCBA    DD E5                         PUSH IX
        MACRO-80 3.43   27-Jul-81       PAGE    1-35


  FCBC    DB 1C                         IN A,(PIOA)
  FCBE    F5                            PUSH AF
  FCBF    CB B7                         RES ELATCH,A            ; EPROM EIN
  FCC1    D3 1C                         OUT (PIOA),A
  FCC3    CD 0097                       CALL PKEY
  FCC6    F1                    CONST0: POP AF
  FCC7    D3 1C                         OUT (PIOA),A
  FCC9    E1                            POP HL                  ; IX NACH HL LADEN
  FCCA    F9                            LD SP,HL
  FCCB    DD E1                         POP IX
  FCCD    E1                            POP HL
  FCCE    79                            LD A,C                  ; ZEICHEN IN A ZURUECK
  FCCF    C9                            RET
                                
                                ;--------------------------------
                                ; EPROM / RAM 0-32k UMSCHALTUNG
                                ; PIOA = PA6
                                
  FCD0    DB 1C                 MEPROM: IN A,(PIOA)
  FCD2    18 08                         JR EPR2
                                
  FCD4    CB 47                 EPROM:  BIT 0,A                 ; EPROM SELEKT
  FCD6    DB 1C                         IN A,(PIOA)
  FCD8    CB B7                         RES ELATCH,A            ; EPROM EIN
  FCDA    28 02                         JR Z,EPR1
  FCDC    CB F7                 EPR2:   SET ELATCH,A            ; EPROM OFF / SRAM ON
  FCDE    D3 1C                 EPR1:   OUT (PIOA),A
  FCE0    C9                            RET
                                
                                ;--------------------------------
                                ; FDC HARTWARE RESET
                                ;--------------------------------
                                
  FCE1                          FDCHRES:
  FCE1    F5                            PUSH AF
  FCE2    3E 47                         LD A,47H                ; WATCHDOG RESET
                                        ;       OUT (WDTCR),A
  FCE4    DB 1C                         IN A,(PIOA)             ; AUF PIOA ALTER WERT
  FCE6    CB 9F                         RES 3,A                 ; FDC RESET BIT AKTIV
  FCE8    D3 1C                         OUT (PIOA),A            ; WIEDER AUSGEBEN AN PIOA
  FCEA    00                            NOP                     ; MIN 250NS RESET
  FCEB    00                            NOP
  FCEC    00                            NOP
  FCED    DB 1C                         IN A,(PIOA)
  FCEF    CB DF                         SET 3,A                 ; RESET BIT ZUR]CKSETZEN ENDE
  FCF1    D3 1C                         OUT (PIOA),A            ; AUSGEBEN AN PIOA
  FCF3    F1                            POP AF
  FCF4    C9                            RET
                                ;--------------------------------
                                ; STATUS AUSGABE IN BIN[R
                                ;--------------------------------
  FCF5    E5                    STFDC:  PUSH HL
  FCF6    D5                            PUSH DE
  FCF7    C5                            PUSH BC
  FCF8    F5                            PUSH AF
  FCF9    57                            LD D,A          ;RETTEN
        MACRO-80 3.43   27-Jul-81       PAGE    1-36


  FCFA    1E 08                         LD E,8H         ; BITANZAHL ZUM DARSTELLEN
  FCFC    CB 7A                 STA0:   BIT 7,D
  FCFE    28 04                         JR Z,STA1
  FD00    3E 31                         LD A,31H        ; ASCII =1
  FD02    18 02                         JR STA2
  FD04    3E 30                 STA1:   LD A,30H        ; ASCII =0
  FD06    D5                    STA2:   PUSH DE
  FD07    4F                            LD C,A
  FD08    CD FC77                       CALL CONOUT
  FD0B    D1                            POP DE
  FD0C    CB 02                         RLC D
  FD0E    1D                            DEC E
  FD0F    20 EB                         JR NZ,STA0
  FD11    0E 2E                         LD C,2EH        ; ABSCHLUSS MIT PUNKT
  FD13    CD FC77                       CALL CONOUT
  FD16    F1                            POP AF
  FD17    C1                            POP BC
  FD18    D1                            POP DE
  FD19    E1                            POP HL
  FD1A    C9                            RET
                                
                                ;--------------------------------
                                ; ASCII / MELDUNG AUSGEBEN
                                
  FD1B    7E                    MSTX:   LD      A,(HL)
  FD1C    FE FF                         CP      0FFH
  FD1E    C8                            RET     Z
  FD1F    E5                            PUSH    HL
  FD20    4F                            LD      C,A
  FD21    CD FC77                       CALL CONOUT
  FD24    E1                            POP     HL
  FD25    23                            INC     HL
  FD26    18 F3                         JR      MSTX
                                ;--------------------------------
                                ; TEXTAUSGABE AUF SIO A
                                
  FD28    F5                    HEX:    PUSH    AF
  FD29    C5                            PUSH    BC
  FD2A    D5                            PUSH    DE
  FD2B    E5                            PUSH    HL
  FD2C    47                            LD      B,A
  FD2D    1F                            RRA
  FD2E    1F                            RRA
  FD2F    1F                            RRA
  FD30    1F                            RRA
  FD31    CD FD42                       CALL    HEX1
  FD34    78                            LD      A,B
  FD35    CD FD42                       CALL    HEX1
  FD38    0E 2E                         LD      C,2EH
  FD3A    CD FC77                       CALL CONOUT
  FD3D    E1                            POP     HL
  FD3E    D1                            POP     DE
  FD3F    C1                            POP     BC
  FD40    F1                            POP     AF
  FD41    C9                            RET
                                        ;-------------
        MACRO-80 3.43   27-Jul-81       PAGE    1-37


  FD42    E6 0F                 HEX1:   AND     0FH
  FD44    C6 30                         ADD     A,30H
  FD46    FE 3A                         CP      3AH
  FD48    38 02                         JR      C,HEX2
  FD4A    C6 07                         ADD     A,07H
  FD4C    C5                            HEX2:   PUSH BC
  FD4D    4F                            LD C,A
  FD4E    CD FC77                       CALL    CONOUT
  FD51    C1                            POP BC
  FD52    C9                            RET
                                
                                ;--------------------------------
                                
  FD53    F5                    TEXTOUT:PUSH AF
  FD54    7E                    TEXT1:  LD A,(HL)
  FD55    FE FF                         CP 0FFH
  FD57    28 0B                         JR Z,TEXT2
  FD59    E5                            PUSH HL
  FD5A    C5                            PUSH BC
  FD5B    4F                            LD C,A
  FD5C    CD FC77                       CALL CONOUT
  FD5F    C1                            POP BC
  FD60    E1                            POP HL
  FD61    23                            INC HL
  FD62    18 F0                         JR TEXT1
  FD64    F1                    TEXT2:  POP AF
  FD65    C9                            RET
                                
                                ;------------------
                                ; LCD 128X128  C AUSGEBEN
                                
  FD66                          LCDOUT:
                                ;IN A,(PIOA)
                                ;       PUSH AF
                                ;       RES 7,A
                                ;       OUT (PIOA),A
                                ;       LD C,'L'
                                ;       CALL CONOUT
                                ;       POP AF
                                ;       OUT (PIOA),A
  FD66    C9                            RET
                                ;--------------------------------
                                ; TASK INTERRUPT ROUTINE
                                ; RETTEN ALLER REGISTER
                                
  FD67    DD E5                 TASK:   PUSH IX         ; 0*
  FD69    ED 73 FFA0                    LD (TSP),SP     ; RETI RUECKSPRUNG RETTEN
  FD6D    31 FFA0                       LD SP,TSP       ; NEUER STACK
  FD70    F5                            PUSH AF         ; 1*
  FD71    DB 1C                         IN A,(PIOA)
  FD73    F5                            PUSH AF         ; 2*
  FD74    CB FF                         SET QA7,A       ; SET EXTERN
  FD76    D3 1C                         OUT (PIOA),A
  FD78    DB F5                         IN A,(LATCH)
  FD7A    F5                            PUSH AF         ; 3*
  FD7B    DB 1C                         IN A,(PIOA)     
        MACRO-80 3.43   27-Jul-81       PAGE    1-38


  FD7D    CB 87                         RES TAS,A
  FD7F    CB BF                         RES QA7,A
  FD81    CB B7                         RES ELATCH,A    ; EPROM EIN 
  FD83    D3 1C                         OUT (PIOA),A
  FD85    C3 043A                       JP TASKEP
                                        ;--------------
  FD88    DB 1C                 TASK1:  IN A,(PIOA)
  FD8A    CB 87                         RES TAS,A
  FD8C    CB FF                         SET QA7,A
  FD8E    D3 1C                         OUT (PIOA),A
  FD90    F1                            POP AF          ; *3
  FD91    D3 F5                         OUT (LATCH),A
  FD93    F1                            POP AF          ; *2
  FD94    D3 1C                         OUT (PIOA),A
  FD96    F1                            POP AF          ; *1
  FD97    DD 2A FFA0                    LD IX,(TSP)
  FD9B    DD F9                         LD SP,IX        ; RETI RUECKSPRUNG LOAD
  FD9D    DD E1                         POP IX          ; *0
  FD9F    ED 4D                         RETI
                                ;---------------------------
  FDA1    0000                  STACK:  DEFW 0000H      ;STACKPIONTER RETTEN
  FDA3    0000                  BSTACK: DEFW 0000H      ;STACK FUER EPROM EIN
  FDA5    0000                  RSTACK: DEFW 0000H      ;STACK FUER EPROM AUS
  FDA7    00 00                 CPUF:   DEFB 0,0
  FDA9    00                    SEQ:    DEFB 0
                                
                                ;---------------------------
                                ; BIT 7 FUER 0=INT., 1= EXT. DRIVE SELECT
                                ; BIT 6 LBA= LOGICAL BLOCK ADDRESSING BIT( 1=LBA MODE, 0=CHS MODE)
                                ; BIT 4 D=DRIVE DESTIGNATION BIT 0=MASTER,1=SLAVE
                                ; BIT 3-0 HS3-HS0 = STARTING HEAD NUMBER
                                
  FDAA    00                    TABLE:  DEFB 00H        ; DRIVE A:
  FDAB    A1                            DEFB 0A1H       ; DRIVE B:
  FDAC    A2                            DEFB 0A2H       ; DRIVE C:
  FDAD    A3                            DEFB 0A3H       ; DRIVE D:
  FDAE    E4                            DEFB 0E4H       ; DRIVE E:
  FDAF    E5                            DEFB 0E5H       ; DRIVE F:
  FDB0    E6                            DEFB 0E6H       ; DRIVE G:
  FDB1    F7                            DEFB 0F7H       ; DRIVE 2 SLAVE H:
                                ;---------------------------
  FDB2    40 00 00 00           SDRES:  DEFB GO_IDLE_STATE,00H,00H,00H,00H,95H
  FDB6    00 95                 
  FDB8    41 00 00 00           SDCMD1: DEFB SEND_OP_COND,00H,00H,00H,00H,01H
  FDBC    00 01                 
  FDBE    4A 00 00 00           SDID:   DEFB 04AH,00H,00H,00H,00H,0FFH
  FDC2    00 FF                 
  FDC4    49 00 00 00           SDCSD:  DEFB 049H,00H,00H,00H,00H,0FFH
  FDC8    00 FF                 
  FDCA    50 00 00 02           SDBL:   DEFB SDBLOCK,00H,00H,02H,00H,01H
  FDCE    00 01                 
  FDD0    58 00 00 00           SDWRITE:DEFB WRITE_BLOCK,00H,00H,00H,00H,01H            ;WRITE_BLOCK
  FDD4    00 01                 
  FDD6    51 00 00 00           SDREAD: DEFB READ_SINGLE_BLOCK,00H,00H,00H,00H,01H      ;READ_SINGLE_BLOCK
  FDDA    00 01                 
                                
        MACRO-80 3.43   27-Jul-81       PAGE    1-39


                                ;------------------------
                                
  FDDC    0A                    MSGTS:  DEFB 0AH
  FDDD    0D                            DEFB 0DH
  FDDE    2A 2A 20 57                   DEFM '** WINI BOOTMONITOR H.WINTERHALTER  -VERS. 1.0- 15.06.07 **'
  FDE2    49 4E 49 20           
  FDE6    42 4F 4F 54           
  FDEA    4D 4F 4E 49           
  FDEE    54 4F 52 20           
  FDF2    48 2E 57 49           
  FDF6    4E 54 45 52           
  FDFA    48 41 4C 54           
  FDFE    45 52 20 20           
  FE02    2D 56 45 52           
  FE06    53 2E 20 31           
  FE0A    2E 30 2D 20           
  FE0E    31 35 2E 30           
  FE12    36 2E 30 37           
  FE16    20 2A 2A              
  FE19    0A                            DEFB 0AH
  FE1A    0D                            DEFB 0DH
  FE1B    2A 2A 20 45                   DEFM '** Erweiterung IDE-Controller       -VERS. 1.1- 28.06.09 **'
  FE1F    72 77 65 69           
  FE23    74 65 72 75           
  FE27    6E 67 20 49           
  FE2B    44 45 2D 43           
  FE2F    6F 6E 74 72           
  FE33    6F 6C 6C 65           
  FE37    72 20 20 20           
  FE3B    20 20 20 20           
  FE3F    2D 56 45 52           
  FE43    53 2E 20 31           
  FE47    2E 31 2D 20           
  FE4B    32 38 2E 30           
  FE4F    36 2E 30 39           
  FE53    20 2A 2A              
  FE56    0A                            DEFB 0AH
  FE57    0D                            DEFB 0DH
  FE58    2A 2A 20 45                   DEFM '** Erweiterung INTERRUPT            -VERS. 1.1- 20.10.09 **'
  FE5C    72 77 65 69           
  FE60    74 65 72 75           
  FE64    6E 67 20 49           
  FE68    4E 54 45 52           
  FE6C    52 55 50 54           
  FE70    20 20 20 20           
  FE74    20 20 20 20           
  FE78    20 20 20 20           
  FE7C    2D 56 45 52           
  FE80    53 2E 20 31           
  FE84    2E 31 2D 20           
  FE88    32 30 2E 31           
  FE8C    30 2E 30 39           
  FE90    20 2A 2A              
  FE93    0A                            DEFB 0AH
  FE94    0D                            DEFB 0DH
  FE95    2A 2A 20 44                   DEFM '** Drive A: MMC-Karte anpassen      -VERS. 1.1- 25.01.17 **'
        MACRO-80 3.43   27-Jul-81       PAGE    1-40


  FE99    72 69 76 65           
  FE9D    20 41 3A 20           
  FEA1    4D 4D 43 2D           
  FEA5    4B 61 72 74           
  FEA9    65 20 61 6E           
  FEAD    70 61 73 73           
  FEB1    65 6E 20 20           
  FEB5    20 20 20 20           
  FEB9    2D 56 45 52           
  FEBD    53 2E 20 31           
  FEC1    2E 31 2D 20           
  FEC5    32 35 2E 30           
  FEC9    31 2E 31 37           
  FECD    20 2A 2A              
  FED0    0A                            DEFB 0AH
  FED1    0D                            DEFB 0DH
  FED2    FF FF                         DEFB 0FFH,0FFH
                                
  FED4    20 45 53 20           MSGTF:  DEFM ' ES FLOPPY-DRIVE    STATUSM=('
  FED8    46 4C 4F 50           
  FEDC    50 59 2D 44           
  FEE0    52 49 56 45           
  FEE4    20 20 20 20           
  FEE8    53 54 41 54           
  FEEC    55 53 4D 3D           
  FEF0    28                    
  FEF1    FF FF                         DEFB 0FFH,0FFH
  FEF3    29 20                 MSGTE:  DEFM ') '
  FEF5    0A                            DEFB 0AH
  FEF6    0D                            DEFB 0DH
  FEF7    FF FF                         DEFB 0FFH,0FFH
  FEF9    2A 2D 4E 4D           MNMI:   DEFM '*-NMI-*'
  FEFD    49 2D 2A              
  FF00    FF FF                         DEFB 0FFH,0FFH
                                
  FF02    20 20 4D 4D           RESNEU: DEFM '  MMC-DRIVE NOT READY'
  FF06    43 2D 44 52           
  FF0A    49 56 45 20           
  FF0E    4E 4F 54 20           
  FF12    52 45 41 44           
  FF16    59                    
  FF17    FF FF                         DEFB 0FFH,0FFH
                                
  FF19    0A 0D                 SYSERR: DEFB 0AH,0DH
  FF1B    20 20 4D 4D                   DEFM '  MMC-DERIVE NO SYSTEM'
  FF1F    43 2D 44 45           
  FF23    52 49 56 45           
  FF27    20 4E 4F 20           
  FF2B    53 59 53 54           
  FF2F    45 4D                 
  FF31    FF FF                         DEFB 0FFH,0FFH
                                
  FF33    20 20 44 52           STAT0:  DEFM '  DRIVE A:   STATUS0=(.'
  FF37    49 56 45 20           
  FF3B    41 3A 20 20           
  FF3F    20 53 54 41           
        MACRO-80 3.43   27-Jul-81       PAGE    1-41


  FF43    54 55 53 30           
  FF47    3D 28 2E              
  FF4A    FF FF                         DEFB 0FFH,0FFH
                                
  FF4C    29 20                 STAT0E: DEFM ') '
  FF4E    0A                            DEFB 0AH
  FF4F    0D                            DEFB 0DH
  FF50    FF FF                         DEFB 0FFH,0FFH
                                
  FF52    20 20 4D 4D           STAT3:  DEFM '  MMC-DRIVE ID (.'
  FF56    43 2D 44 52           
  FF5A    49 56 45 20           
  FF5E    49 44 20 28           
  FF62    2E                    
  FF63    FF FF                         DEFB 0FFH,0FFH
                                
  FF65    29 20                 STAT3E: DEFM ') '
  FF67    0A                            DEFB 0AH
  FF68    0D                            DEFB 0DH
  FF69    FF FF                         DEFB 0FFH,0FFH
                                
                                
  FF6B    0A 0D FF FF           CRLF:   DEFB 0AH,0DH,0FFH,0FFH
                                
  FF6F    13 FF FF              CR:     DEFB 13H,0FFH,0FFH
  FF72    0F 00 28              SEEKC:  DEFB 0FH,00H,28H
  0003                          SEEKL   EQU $-SEEKC
                                
  FF75    03 FA ED              SPY:    DEFB 03H,0FAH,0EDH
  0003                          SPYL    EQU $-SPY
                                
  FF78    0A 0D 20 28           STOP:   DEFB 0AH,0DH,20H,28H,0FFH,029H
  FF7C    FF 29                 
  FF7E    20 53 45 43                   DEFM ' SEC. ERROR '
  FF82    2E 20 45 52           
  FF86    52 4F 52 20           
  FF8A    0A 0D FF FF                   DEFB 0AH,0DH,0FFH,0FFH
                                
  FF8E    20 43 6F 6D           TCOM:   DEFM ' Com. '
  FF92    2E 20                 
  FF94    0A 0D FF FF                   DEFB 0AH,0DH,0FFH,0FFH
                                
  FF98    20 20 42 49           BIOSERR:DEFM '  BIOY-Aufruf ERROR '
  FF9C    4F 59 2D 41           
  FFA0    75 66 72 75           
  FFA4    66 20 45 52           
  FFA8    52 4F 52 20           
  FFAC    FF FF                         DEFB 0FFH,0FFH
                                
                                ;-------------------------
                                ; FTAB=COM,DRV,C,H,R,N,EOT,GPL,DTL
                                ; DRIVE:        DEFB 0
  FFAE    00 00 00 00           FTAB:   DEFB 0,0,0,0,0,0,0,0,0
  FFB2    00 00 00 00           
  FFB6    00                    
  FFB7    00                    BCPM:   DEFB 0
        MACRO-80 3.43   27-Jul-81       PAGE    1-42


                                
                                ; IF $ GT 0FFF0H OR $ LT START
                                ; .PRINTX "   ### ORIGIN OF HDBIOS TOO HIGHY! ###"
                                ; ENDIF
                                
                                END
        MACRO-80 3.43   27-Jul-81       PAGE    S


Macros:

Symbols:
F814    B1              F82F    B10             F832    B11             
F835    B12             F838    B13             F817    B2              
F81A    B3              F81D    B4              F820    B5              
F823    B6              F826    B7              F829    B8              
F82C    B9              0047    BAUD1           0047    BAUD2           
0047    BAUD3           00C7    BAUD4           FFB7    BCPM            
0005    BDOSEN          03C5    BIOS            FF98    BIOSERR         
FFEF    BIOSSP          F83B    BOOT1           F85A    BOOTN           
FDA3    BSTACK          F961    CARDDELAY       FA11    CHKERR          
0090    CMD_DIAGN       00EC    CMD_IDENT       0091    CMD_INITIA      
0020    CMD_READSEC     0070    CMD_SEEK        0030    CMD_WRITESEC    
F94C    COMMAND         F9D3    COMUP           FC94    CONIN           
FC77    CONOUT          FCAE    CONST           FCC6    CONST0          
009E    CONW            00B6    CONW1           FDA7    CPUF            
FF6F    CR              02FE    CR1             FF6B    CRLF            
0010    CTC0            0011    CTC1            0012    CTC2            
0013    CTC3            F8CE    DB01            F91F    DB02            
F906    DB03            F8F1    DB04            F894    DBOOT           
00F4    DCI             F8CA    DIV             F8C1    DIVI            
FFF3    DMA             FFAD    DRIVE           0007    DRVS            
F899    DTEST           0006    ELATCH          FFF5    ENA             
0040    EOFF            0000    EON             FCDE    EPR1            
FCDC    EPR2            FCD4    EPROM           0116    ERRTEX          
0389    ETEX            0060    EXOFF           056F    F08FB           
0020    FDC             FCE1    FDCHRES         0576    FDCP1           
0574    FDCP2           FFF0    FIRST           0004    FREI            
FFAE    FTAB            F96F    GETBYTE         0040    GO_IDLE_STATE   
F92C    GROUP           FD28    HEX             FD42    HEX1            
FD4C    HEX2            F9D1    HOK             F9CF    HOK0            
F9CB    HOKE            F9C9    HOKE0           F972    HOME            
F998    HOME0           F996    HOMHD           FFA6    HSTDMA          
FFAC    HSTDSK          FFA8    HSTSEC          FFAA    HSTTRK          
00F0    IDE             00FD    IDECHI          00FC    IDECLO          
00FF    IDECMD          00F8    IDEDAT          00F6    IDEDOR          
00F9    IDEERR          FC05    IDERES          FC0A    IDERES1         
00FA    IDESCNT         00FE    IDESDH          00FB    IDESNUM         
00FF    IDESTAT         FBA4    IDE_SET01       FB97    IDE_SET_LBA     
047A    INITIA          006B    INP0            006C    INP1            
008B    INP2            0003    IOBYTE          0000    KANAL0          
0001    KANAL1          0003    KANAL3          0004    KANAL4          
0005    KANAL5          0056    KEYRD           00F5    LATCH           
0060    LCD             02D1    LCD0            02C2    LCD00           
02D5    LCD1            FD66    LCDOUT          02D7    LCDRY           
02DA    LCDRY0          02E0    LCDRY1          02E9    LCDRY2          
01A7    LCDS            02EB    LCR             0014    LETEX           
0322    LHEX            033A    LHEX1           0344    LHEX2           
FC52    LIST            00C8    LISTA           FC4C    LISTST          
015C    LOS             030E    LPOS            0014    LSDOK           
001F    LSTEX           FCD0    MEPROM          FEF9    MNMI            
FEF3    MSGTE           FED4    MSGTF           FDDC    MSGTS           
0589    MSTAT           0015    MSTIME          FD1B    MSTX            
FFB0    NBUF            F916    NOSYS           0159    NOT             
004C    OUT0            056E    PAUS            0571    PAUS01          
001C    PIOA            001E    PIOB            0097    PKEY            
        MACRO-80 3.43   27-Jul-81       PAGE    S-1


0143    PLISTST         00C7    PRINT           0007    QA7             
8000    RAM             0021    RAMH            0000    RAML            
0000    RAMSTART        FA4D    RD00            FA4F    RD01            
FA22    READ            FA19    READH2          F9E6    READHST         
0051    READ_SINGLE_BLOC 0000   REG1            00C1    REG3            
0044    REG4            00EA    REG5            FF02    RESNEU          
0003    RFDC            FDA5    RSTACK          0002    RT              
FB95    RW01            FB6D    RW02            FB77    RW03            
FB5E    RWSETUP         0561    RY01            FFF1    SA              
00EF    SCDP            00EE    SCRP            FDCA    SDBL            
0050    SDBLOCK         0020    SDC             FDB8    SDCMD1          
F958    SDCOM           FDC4    SDCSD           0552    SDCSD0          
04B3    SDERR           FDBE    SDID            04BB    SDINI1          
039D    SDNEU           03B1    SDOK            FA5C    SDRD02          
FA6B    SDRD03          051C    SDRDID          FDD6    SDREAD          
FDB2    SDRES           FAE3    SDWR01          FAF2    SDWR02          
FAFA    SDWR03          FDD0    SDWRITE         0485    SD_INI          
F966    SD_STATUS       FFB6    SECBUF          FFF9    SECL            
0200    SECSIZE         F9E0    SECTRAN         FF72    SEEKC           
0003    SEEKL           FFBB    SEKTORHH        FFBA    SEKTORHL        
FFB9    SEKTORLH        FFB8    SEKTORLL        FC19    SELDR           
FB06    SELDSK          FC49    SELRET          F963    SENDBYTE        
0041    SEND_OP_COND    FDA9    SEQ             FB10    SETDMA          
FB1E    SETSEC          FB15    SETSEC8         FB0B    SETTRK          
0018    SIOA            001A    SIOB            0060    SIOEX           
0018    SIORES          01F1    SIOS            0005    SIOX            
0021    SIOX1           0043    SIOX2           0025    SIOY            
0041    SIOY1           FB3A    SL01            FB46    SL02            
FB52    SL03            FB23    SL32            FB2E    SL321           
FB3E    SL322           FB4A    SL323           FB56    SL324           
FFF2    SM              FF75    SPY             0003    SPYL            
F967    SS1             FCFC    STA0            FD04    STA1            
FD06    STA2            FDA1    STACK           0596    START           
FFF7    STARTA          FF33    STAT0           FF4C    STAT0E          
FF52    STAT3           FF65    STAT3E          FFAF    STATUS          
036A    STEX            FCF5    STFDC           FF78    STOP            
FF19    SYSERR          0005    TA16            FDAA    TABLE           
0000    TAS             044A    TAS01           0463    TAS12           
0465    TAS13           FD67    TASK            FD88    TASK1           
0474    TASK14          043A    TASKEP          FFA2    TASKSP          
FF8E    TCOM            0006    TDRV            034F    TEX             
0363    TEXDR           FD54    TEXT1           FD64    TEXT2           
FD53    TEXTOUT         F99D    TI1             0004    TIME1           
0004    TIME2           0004    TIME3           000F    TIME4           
0080    TPABUF          005C    TPAFCB          FFA5    TRACKH          
FFA4    TRACKL          FFAE    TRACKN          FFA0    TSP             
0064    TX2             0014    TXL             0080    URCS            
0004    USRDRV          00D9    W0              00D7    W00             
00E0    W1              0113    W3              0100    W4              
010C    W5              FBD9    WAITBS1         FBD5    WAITBSY         
FBC9    WAITDR1         FBC4    WAITDRQ         FBFF    WAITEND         
FBF9    WAITERR         FBEE    WAITRD1         FBE5    WAITRDY         
00F1    WDTCR           00F0    WDTMR           FACE    WR00            
FAD1    WR01            FAA3    WRITE           FA74    WRITEHST        
0058    WRITE_BLOCK     



No Fatal error(s)


                                                                                                                                                                                                                                                                                        